// THIS FILE IS AUTOGENERATED //
#include "../interface/GeneralTree.h"
// STARTCUSTOM INCLUDE

#include <iostream>

TString GeneralTree::csvShiftName(GeneralTree::csvShift shift) 
{
  switch (shift) {
    case csvCent        : return "central"      ;
    case csvJESup       : return "up_jes"       ;
    case csvJESdown     : return "down_jes"     ;
    case csvLFup        : return "up_lf"        ;
    case csvLFdown      : return "down_lf"      ;
    case csvHFup        : return "up_hf"        ;
    case csvHFdown      : return "down_hf"      ;
    case csvHFStats1up  : return "up_hfstats1"  ;
    case csvHFStats1down: return "down_hfstats1";
    case csvHFStats2up  : return "up_hfstats2"  ;
    case csvHFStats2down: return "down_hfstats2";
    case csvLFStats1up  : return "up_lfstats1"  ;
    case csvLFStats1down: return "down_lfstats1";
    case csvLFStats2up  : return "up_lfstats2"  ;
    case csvLFStats2down: return "down_lfstats2";
    case csvCErr1up     : return "up_cferr1"    ;
    case csvCErr1down   : return "down_cferr1"  ;
    case csvCErr2up     : return "up_cferr2"    ;
    case csvCErr2down   : return "down_cferr2"  ;
    default : return "central";
  }
}
//ENDCUSTOM
TString jesName(shiftjes e) {
  switch(e) {
    case shiftjes::kNominal : return "Nominal";
    case shiftjes::kJESTotalUp : return "JESTotalUp";
    case shiftjes::kJESTotalDown : return "JESTotalDown";
    case shiftjes::kJESAbsoluteMPFBiasUp : return "JESAbsoluteMPFBiasUp";
    case shiftjes::kJESAbsoluteMPFBiasDown : return "JESAbsoluteMPFBiasDown";
    case shiftjes::kJESAbsoluteScaleUp : return "JESAbsoluteScaleUp";
    case shiftjes::kJESAbsoluteScaleDown : return "JESAbsoluteScaleDown";
    case shiftjes::kJESAbsoluteStatUp : return "JESAbsoluteStatUp";
    case shiftjes::kJESAbsoluteStatDown : return "JESAbsoluteStatDown";
    case shiftjes::kJESFlavorQCDUp : return "JESFlavorQCDUp";
    case shiftjes::kJESFlavorQCDDown : return "JESFlavorQCDDown";
    case shiftjes::kJESFragmentationUp : return "JESFragmentationUp";
    case shiftjes::kJESFragmentationDown : return "JESFragmentationDown";
    case shiftjes::kJESPileUpDataMCUp : return "JESPileUpDataMCUp";
    case shiftjes::kJESPileUpDataMCDown : return "JESPileUpDataMCDown";
    case shiftjes::kJESPileUpPtBBUp : return "JESPileUpPtBBUp";
    case shiftjes::kJESPileUpPtBBDown : return "JESPileUpPtBBDown";
    case shiftjes::kJESPileUpPtEC1Up : return "JESPileUpPtEC1Up";
    case shiftjes::kJESPileUpPtEC1Down : return "JESPileUpPtEC1Down";
    case shiftjes::kJESPileUpPtEC2Up : return "JESPileUpPtEC2Up";
    case shiftjes::kJESPileUpPtEC2Down : return "JESPileUpPtEC2Down";
    case shiftjes::kJESPileUpPtRefUp : return "JESPileUpPtRefUp";
    case shiftjes::kJESPileUpPtRefDown : return "JESPileUpPtRefDown";
    case shiftjes::kJESRelativeFSRUp : return "JESRelativeFSRUp";
    case shiftjes::kJESRelativeFSRDown : return "JESRelativeFSRDown";
    case shiftjes::kJESRelativeJEREC1Up : return "JESRelativeJEREC1Up";
    case shiftjes::kJESRelativeJEREC1Down : return "JESRelativeJEREC1Down";
    case shiftjes::kJESRelativePtBBUp : return "JESRelativePtBBUp";
    case shiftjes::kJESRelativePtBBDown : return "JESRelativePtBBDown";
    case shiftjes::kJESRelativePtEC1Up : return "JESRelativePtEC1Up";
    case shiftjes::kJESRelativePtEC1Down : return "JESRelativePtEC1Down";
    case shiftjes::kJESRelativePtEC2Up : return "JESRelativePtEC2Up";
    case shiftjes::kJESRelativePtEC2Down : return "JESRelativePtEC2Down";
    case shiftjes::kJESRelativeStatECUp : return "JESRelativeStatECUp";
    case shiftjes::kJESRelativeStatECDown : return "JESRelativeStatECDown";
    case shiftjes::kJESRelativeStatFSRUp : return "JESRelativeStatFSRUp";
    case shiftjes::kJESRelativeStatFSRDown : return "JESRelativeStatFSRDown";
    case shiftjes::kJESSinglePionECALUp : return "JESSinglePionECALUp";
    case shiftjes::kJESSinglePionECALDown : return "JESSinglePionECALDown";
    case shiftjes::kJESSinglePionHCALUp : return "JESSinglePionHCALUp";
    case shiftjes::kJESSinglePionHCALDown : return "JESSinglePionHCALDown";
    case shiftjes::kJESTimePtEtaUp : return "JESTimePtEtaUp";
    case shiftjes::kJESTimePtEtaDown : return "JESTimePtEtaDown";
    default : return "N";
  }
}
TString jetringsName(shiftjetrings e) {
  switch(e) {
    case shiftjetrings::k0 : return "0";
    case shiftjetrings::k1 : return "1";
    case shiftjetrings::k2 : return "2";
    case shiftjetrings::k3 : return "3";
    case shiftjetrings::k4 : return "4";
    default : return "N";
  }
}
TString pfsName(shiftpfs e) {
  switch(e) {
    case shiftpfs::k0 : return "0";
    case shiftpfs::k1 : return "1";
    case shiftpfs::k2 : return "2";
    case shiftpfs::k3 : return "3";
    case shiftpfs::k4 : return "4";
    default : return "N";
  }
}
GeneralTree::GeneralTree() {
// STARTCUSTOM CONSTRUCTOR
    for (auto ibeta : ibetas) {
        for (auto N : Ns) {
            for (auto order : orders) {
                ECFParams p;
                p.ibeta = ibeta;
                p.N = N;
                p.order = order;
                ecfParams.push_back(p);
                fjECFNs[p] = new float[2];
            }
        }
    }

    for (unsigned iShift=0; iShift!=bNShift; ++iShift) {
        for (unsigned iJet=0; iJet!=bNJet; ++iJet) {
            for (unsigned iTags=0; iTags!=bNTags; ++iTags) {
                BTagParams p;
                p.jet = (BTagJet)iJet;
                p.tag = (BTagTags)iTags;
                p.shift = (BTagShift)iShift;
                btagParams.push_back(p);
                sf_btags[p] = 1;
            }
        }
    }

    for (unsigned iShift=0; iShift<nCsvShifts; iShift++) {
        csvShift shift = csvShifts[iShift];
        sf_csvWeights[shift] = 1;
    }
// ENDCUSTOM
  Reset();
}
GeneralTree::~GeneralTree() {
// STARTCUSTOM DESTRUCTOR
    for (auto p : ecfParams) {
        delete[] fjECFNs[p];
    }
// ENDCUSTOM
}
void GeneralTree::SetAuxTree(TTree *t) {
// STARTCUSTOM AUX
    for (auto p : ecfParams) {
        TString ecfn(makeECFString(p));
        t->Branch("fj"+ecfn,&(fjECFNs[p][0]),"fj"+ecfn+"/F");
    }
// ENDCUSTOM
}
void GeneralTree::Reset() {
// STARTCUSTOM RESET
    for (auto p : ecfParams) {
      for (int i = 0; i != 2; ++i)
        fjECFNs[p][i] = -1;
    }

    for (auto p : btagParams) {
        sf_btags[p] = 1;
    }
    for (unsigned iShift=0; iShift<nCsvShifts; iShift++) {
        csvShift shift = csvShifts[iShift];
        sf_csvWeights[shift] = 1;
    }
    for (auto iter=signal_weights.begin(); iter!=signal_weights.end(); ++iter) {
        signal_weights[iter->first] = 1;
    }
// ENDCUSTOM
  runNumber = 0;
  lumiNumber = 0;
  eventNumber = -99;
  isData = 0;
  npv = 0;
  pu = 0;
  rho = -99;
  mcWeight = -99;
  trigger = 0;
  metFilter = 0;
  comFilter = 0;
  egmFilter = 0;
  filter_maxRecoil = -99;
  filter_whichRecoil = 0;
  badECALFilter = 1;
  category = 0;
  npdf = 0;
  nscale = 0;
  pdfup = -99;
  pdfdow = -99;
  HTTot = -99;
  HLT_PFHT1050 = -99;
  HLT_PFJet500 = -99;
  sf_ewkV = 1;
  sf_qcdV = 1;
  sf_btag = 1;
  sf_lepID = 1;
  sf_lepIso = 1;
  sf_lepTrack = 1;
  sf_pho = 1;
  sf_trig_HT1050 = 1;
  sf_l1Prefire = 1;
  sf_pu = 1;
  sf_npv = 1;
  sf_tt = 1;
  sf_phoPurity = 1;
  hemveto = 0;
  lheht = -99;
  sumETRaw = -99;
  pfmetRaw = -99;
  sphericity = -99;
  calomet = -99;
  calometphi = -99;
  pfcalobalance = -99;
  sumET = -99;
  trkmet = -99;
  trkmetphi = -99;
  trkmetDZ = -99;
  trkmetDZphi = -99;
  genmet = -99;
  genmetphi = -99;
  whichRecoil = 0;
  trueGenBosonPt = -99;
  genBosonPt = -99;
  genBosonEta = -99;
  genBosonMass = -99;
  genBosonPhi = -99;
  genJet1Pt = -99;
  genJet2Pt = -99;
  genJet1Eta = -99;
  genJet2Eta = -99;
  genJet1Phi = -99;
  genJet2Phi = -99;
  SUEP_mult_eta = -99;
  SUEP_mult_phi = -99;
  SUEP_mult_nconst = 0;
  SUEP_mult_spher = -99;
  SUEP_pt_eta = -99;
  SUEP_pt_phi = -99;
  SUEP_pt_nconst = 0;
  SUEP_pt_spher = -99;
  SUEP_isr_pt = -99;
  SUEP_isr_m = -99;
  SUEP_isr_eta = -99;
  SUEP_isr_phi = -99;
  SUEP_isr_nconst = 0;
  SUEP_isr_spher = -99;
  nJetMax = 0;
  nTrk = 0;
  nFatJet = 0;
  nFatJetTrunc = 0;
  nHF = 0;
  nB = 0;
  nBGenJets = 0;
  nStatus2BHadrons = 0;
  genFatJetPt = -99;
  genFatJetNProngs = 0;
  nGenJet = 0;
  nLoosePhoton = 0;
  nTightPhoton = 0;
  loosePho1IsTight = 0;
  loosePho1Pt = -99;
  loosePho1Eta = -99;
  loosePho1Phi = -99;
  loosePho1r9 = -99;
  loosePho1chIso = -99;
  loosePho1nhIso = -99;
  loosePho1phIso = -99;
  loosePho1hOverE = -99;
  loosePho1sieie = -99;
  loosePho1SelBit = 0;
  looseGenPho1PdgId = 0;
  loosePhoeveto = 0;
  nFakePhoton = 0;
  FakePho1Pt = -99;
  FakePho1Eta = -99;
  FakePho1Phi = -99;
  genPhotonPt = -99;
  genPhotonEta = -99;
  genPhotonPhi = -99;
  nLooseLep = 0;
  nLooseElectron = 0;
  nLooseMuon = 0;
  nTightLep = 0;
  nTightElectron = 0;
  nTightMuon = 0;
  diLepMass = -99;
  nTau = 0;
  genPho1Pt = -99;
  genPho1Eta = -99;
  genPho1Phi = -99;
  vtxNTrk = 0;
  vtxScore = -99;
  vtxChi2 = -99;
  scaleUp = 1;
  scaleDown = 1;
  pdfUp = 1;
  pdfDown = 1;
  lheHT = -99;
  lheNjets = 0;
  isGS = 0;
  for (int iA=0; iA!=200; ++iA) {
    hbbconstpt[iA] = 0;
    hbbconsteta[iA] = 0;
    hbbconstphi[iA] = 0;
    hbbconste[iA] = 0;
    hbbconstid[iA] = 0;
  }
  for (int iA=0; iA!=4; ++iA) {
    muonPt[iA] = -99;
    muonEta[iA] = -99;
    muonPhi[iA] = -99;
    muonSelBit[iA] = 0;
    muonPdgId[iA] = 0;
    muonD0[iA] = -99;
    muonDZ[iA] = -99;
    muonIsSoftMuon[iA] = 0;
    muonCombIso[iA] = -99;
    muonSfLoose[iA] = -99;
    muonSfMedium[iA] = -99;
    muonSfTight[iA] = -99;
    muonSfUnc[iA] = -99;
    muonSfReco[iA] = -99;
    muTrigMatch[iA] = 0;
    electronPt[iA] = -99;
    electronEta[iA] = -99;
    electronPhi[iA] = -99;
    electronSelBit[iA] = 0;
    electronPdgId[iA] = 0;
    electronPhoMatch[iA] = 0;
    electronLPhoMatch[iA] = 0;
    electronSfLoose[iA] = -99;
    electronSfMedium[iA] = -99;
    electronSfTight[iA] = -99;
    electronSfUnc[iA] = -99;
    electronSfReco[iA] = -99;
    electronSfMvaWP90[iA] = -99;
    electronSfMvaWP80[iA] = -99;
    electronD0[iA] = -99;
    electronDZ[iA] = -99;
    electronNMissingHits[iA] = 0;
    electronTripleCharge[iA] = 0;
    electronCombIso[iA] = -99;
    eleTrigMatch[iA] = 0;
    tauPt[iA] = -99;
    tauEta[iA] = -99;
    tauPhi[iA] = -99;
  }
  for (int iA=0; iA!=2; ++iA) {
    fjTau32[iA] = -99;
    fjTau21[iA] = -99;
    fjTau32SD[iA] = -99;
    fjTau21SD[iA] = -99;
    fjRho[iA] = -99;
    fjRawRho[iA] = -99;
    fjRho2[iA] = -99;
    fjRawRho2[iA] = -99;
    fjPhi[iA] = -99;
    fjEta[iA] = -99;
    fjNconst[iA] = -99;
    fjQ[iA] = -99;
    fjMaxCSV[iA] = -99;
    fjSubMaxCSV[iA] = -99;
    fjMinCSV[iA] = -99;
    fjDoubleCSV[iA] = -99;
    fjDeepB[iA] = -99;
    fjDeepProbH[iA] = -99;
    fjgbb[iA] = 0;
    fjNbs[iA] = 0;
    fjGenPt[iA] = -99;
    fjGenSize[iA] = -99;
    fjIsMatched[iA] = 0;
    fjGenWPt[iA] = -99;
    fjGenWSize[iA] = -99;
    fjIsWMatched[iA] = 0;
    fjHighestPtGen[iA] = 0;
    fjHighestPtGenPt[iA] = -99;
    fjIsTight[iA] = 0;
    fjIsLoose[iA] = 0;
    fjRawPt[iA] = -99;
    fjNHF[iA] = 0;
    fjHTTMass[iA] = -99;
    fjHTTFRec[iA] = -99;
    fjIsClean[iA] = 0;
    fjNPartons[iA] = 0;
    fjNBPartons[iA] = 0;
    fjNCPartons[iA] = 0;
    fjPartonM[iA] = -99;
    fjPartonPt[iA] = -99;
    fjPartonEta[iA] = -99;
    fjGenNumB[iA] = 0;
  }
  for (int iA=0; iA!=6; ++iA) {
    scale[iA] = 1;
  }
  for (int iA=0; iA!=9; ++iA) {
    qcd[iA] = -99;
  }
  for (int iA=0; iA!=3; ++iA) {
    trkPt[iA] = -99;
    trkEta[iA] = -99;
    trkPhi[iA] = -99;
  }
  for (int iA=0; iA!=30; ++iA) {
    jetEta[iA] = -99;
    jetPhi[iA] = -99;
    jetGenPt[iA] = -99;
    jetIsTight[iA] = 0;
    jetIsIso[iA] = 0;
    GenJetPt[iA] = -99;
    GenJetEta[iA] = -99;
    GenJetPhi[iA] = -99;
  }
  for (int iS=0; iS!=3; ++iS) {
    pfmet[iS] = -99;
    pfmetphi[iS] = -99;
    pfmetnomu[iS] = -99;
    puppimet[iS] = -99;
    puppimetphi[iS] = -99;
    puppiUWmag[iS] = -99;
    puppiUZmag[iS] = -99;
    puppiUAmag[iS] = -99;
    puppiUmag[iS] = -99;
    puppiUWphi[iS] = -99;
    puppiUZphi[iS] = -99;
    puppiUAphi[iS] = -99;
    puppiUphi[iS] = -99;
    pfUWmag[iS] = -99;
    pfUZmag[iS] = -99;
    pfUAmag[iS] = -99;
    pfUmag[iS] = -99;
    pfUWphi[iS] = -99;
    pfUZphi[iS] = -99;
    pfUAphi[iS] = -99;
    pfUphi[iS] = -99;
    dphipfmet[iS] = 999;
    dphipuppimet[iS] = 999;
    dphipuppiUW[iS] = 999;
    dphipuppiUZ[iS] = 999;
    dphipuppiUA[iS] = 999;
    dphipfUW[iS] = 999;
    dphipfUZ[iS] = 999;
    dphipfUA[iS] = 999;
    dphipuppiU[iS] = 999;
    dphipfU[iS] = 999;
    SUEP_mult_pt[iS] = -99;
    SUEP_mult_m[iS] = -99;
    SUEP_pt_pt[iS] = -99;
    SUEP_pt_m[iS] = -99;
    mT[iS] = -99;
  }
  for (int iS=0; iS!=43; ++iS) {
    nJet[iS] = 0;
    nIsoJet[iS] = 0;
    jetht[iS] = -99;
  }
  for (int iS=0; iS!=43; ++iS) {
    for (int iA=0; iA!=2; ++iA) {
      fjMSD[iS][iA] = -99;
      fjMSD_corr[iS][iA] = -99;
      fjPt[iS][iA] = -99;
      fjM[iS][iA] = -99;
    }
  }
  for (int iS=0; iS!=43; ++iS) {
    for (int iA=0; iA!=30; ++iA) {
      jetPt[iS][iA] = -99;
      jetM[iS][iA] = -99;
    }
  }
}
void GeneralTree::WriteTree(TTree *t) {
  treePtr = t;
// STARTCUSTOM WRITE
    for (auto iter=signal_weights.begin(); iter!=signal_weights.end(); ++iter) {
        Book("rw_"+iter->first,&(signal_weights[iter->first]),"rw_"+iter->first+"/F");
    }
    for (auto p : ecfParams) {
        TString ecfn(makeECFString(p));
        Book("fj"+ecfn,fjECFNs[p],"fj"+ecfn+"["+fjTreeSize()+"]/F");
    }

    for (auto p : btagParams) {
        TString btagn(makeBTagSFString(p));
        Book(btagn,&(sf_btags[p]),btagn+"/F");
    }

    if (btagWeights) {
        for (unsigned iShift=0; iShift<nCsvShifts; iShift++) {
            csvShift shift = csvShifts[iShift];
            TString csvWeightString = makeCsvWeightString(shift, useCMVA);
            Book(csvWeightString, &(sf_csvWeights[shift]), csvWeightString+"/F");
        }
    }
// ENDCUSTOM
  Book("runNumber",&runNumber,"runNumber/I");
  Book("lumiNumber",&lumiNumber,"lumiNumber/I");
  Book("eventNumber",&eventNumber,"eventNumber/l");
  Book("isData",&isData,"isData/I");
  Book("npv",&npv,"npv/I");
  Book("pu",&pu,"pu/I");
  Book("rho",&rho,"rho/F");
  Book("mcWeight",&mcWeight,"mcWeight/F");
  Book("trigger",&trigger,"trigger/I");
  Book("metFilter",&metFilter,"metFilter/I");
  Book("comFilter",&comFilter,"comFilter/I");
  Book("egmFilter",&egmFilter,"egmFilter/I");
  Book("filter_maxRecoil",&filter_maxRecoil,"filter_maxRecoil/F");
  Book("filter_whichRecoil",&filter_whichRecoil,"filter_whichRecoil/I");
  Book("badECALFilter",&badECALFilter,"badECALFilter/I");
  Book("category",&category,"category/I");
  Book("npdf",&npdf,"npdf/I");
  Book("nscale",&nscale,"nscale/I");
  Book("pdfup",&pdfup,"pdfup/F");
  Book("pdfdow",&pdfdow,"pdfdow/F");
  Book("qcd",qcd,"qcd["+TString("9")+"]/F");
  Book("HTTot",&HTTot,"HTTot/F");
  Book("HLT_PFHT1050",&HLT_PFHT1050,"HLT_PFHT1050/O");
  Book("HLT_PFJet500",&HLT_PFJet500,"HLT_PFJet500/O");
  Book("sf_ewkV",&sf_ewkV,"sf_ewkV/F");
  Book("sf_qcdV",&sf_qcdV,"sf_qcdV/F");
  Book("sf_btag",&sf_btag,"sf_btag/F");
  Book("sf_lepID",&sf_lepID,"sf_lepID/F");
  Book("sf_lepIso",&sf_lepIso,"sf_lepIso/F");
  Book("sf_lepTrack",&sf_lepTrack,"sf_lepTrack/F");
  Book("sf_pho",&sf_pho,"sf_pho/F");
  Book("sf_trig_HT1050",&sf_trig_HT1050,"sf_trig_HT1050/F");
  Book("sf_l1Prefire",&sf_l1Prefire,"sf_l1Prefire/F");
  Book("sf_pu",&sf_pu,"sf_pu/F");
  Book("sf_npv",&sf_npv,"sf_npv/F");
  Book("sf_tt",&sf_tt,"sf_tt/F");
  Book("sf_phoPurity",&sf_phoPurity,"sf_phoPurity/F");
  Book("hemveto",&hemveto,"hemveto/I");
  Book("lheht",&lheht,"lheht/F");
  Book("sumETRaw",&sumETRaw,"sumETRaw/F");
  Book("pfmetRaw",&pfmetRaw,"pfmetRaw/F");
  Book("sphericity",&sphericity,"sphericity/F");
  Book("pfmet",&(pfmet[0]),"pfmet/F");
  Book("pfmet_JESTotalUp",&(pfmet[1]),"pfmet_JESTotalUp/F");
  Book("pfmet_JESTotalDown",&(pfmet[2]),"pfmet_JESTotalDown/F");
  Book("pfmetphi",&(pfmetphi[0]),"pfmetphi/F");
  Book("pfmetphi_JESTotalUp",&(pfmetphi[1]),"pfmetphi_JESTotalUp/F");
  Book("pfmetphi_JESTotalDown",&(pfmetphi[2]),"pfmetphi_JESTotalDown/F");
  Book("pfmetnomu",&(pfmetnomu[0]),"pfmetnomu/F");
  Book("pfmetnomu_JESTotalUp",&(pfmetnomu[1]),"pfmetnomu_JESTotalUp/F");
  Book("pfmetnomu_JESTotalDown",&(pfmetnomu[2]),"pfmetnomu_JESTotalDown/F");
  Book("puppimet",&(puppimet[0]),"puppimet/F");
  Book("puppimet_JESTotalUp",&(puppimet[1]),"puppimet_JESTotalUp/F");
  Book("puppimet_JESTotalDown",&(puppimet[2]),"puppimet_JESTotalDown/F");
  Book("puppimetphi",&(puppimetphi[0]),"puppimetphi/F");
  Book("puppimetphi_JESTotalUp",&(puppimetphi[1]),"puppimetphi_JESTotalUp/F");
  Book("puppimetphi_JESTotalDown",&(puppimetphi[2]),"puppimetphi_JESTotalDown/F");
  Book("calomet",&calomet,"calomet/F");
  Book("calometphi",&calometphi,"calometphi/F");
  Book("pfcalobalance",&pfcalobalance,"pfcalobalance/F");
  Book("sumET",&sumET,"sumET/F");
  Book("trkmet",&trkmet,"trkmet/F");
  Book("trkmetphi",&trkmetphi,"trkmetphi/F");
  Book("trkmetDZ",&trkmetDZ,"trkmetDZ/F");
  Book("trkmetDZphi",&trkmetDZphi,"trkmetDZphi/F");
  Book("genmet",&genmet,"genmet/F");
  Book("genmetphi",&genmetphi,"genmetphi/F");
  Book("whichRecoil",&whichRecoil,"whichRecoil/I");
  Book("puppiUWmag",&(puppiUWmag[0]),"puppiUWmag/F");
  Book("puppiUWmag_JESTotalUp",&(puppiUWmag[1]),"puppiUWmag_JESTotalUp/F");
  Book("puppiUWmag_JESTotalDown",&(puppiUWmag[2]),"puppiUWmag_JESTotalDown/F");
  Book("puppiUZmag",&(puppiUZmag[0]),"puppiUZmag/F");
  Book("puppiUZmag_JESTotalUp",&(puppiUZmag[1]),"puppiUZmag_JESTotalUp/F");
  Book("puppiUZmag_JESTotalDown",&(puppiUZmag[2]),"puppiUZmag_JESTotalDown/F");
  Book("puppiUAmag",&(puppiUAmag[0]),"puppiUAmag/F");
  Book("puppiUAmag_JESTotalUp",&(puppiUAmag[1]),"puppiUAmag_JESTotalUp/F");
  Book("puppiUAmag_JESTotalDown",&(puppiUAmag[2]),"puppiUAmag_JESTotalDown/F");
  Book("puppiUmag",&(puppiUmag[0]),"puppiUmag/F");
  Book("puppiUmag_JESTotalUp",&(puppiUmag[1]),"puppiUmag_JESTotalUp/F");
  Book("puppiUmag_JESTotalDown",&(puppiUmag[2]),"puppiUmag_JESTotalDown/F");
  Book("puppiUWphi",&(puppiUWphi[0]),"puppiUWphi/F");
  Book("puppiUWphi_JESTotalUp",&(puppiUWphi[1]),"puppiUWphi_JESTotalUp/F");
  Book("puppiUWphi_JESTotalDown",&(puppiUWphi[2]),"puppiUWphi_JESTotalDown/F");
  Book("puppiUZphi",&(puppiUZphi[0]),"puppiUZphi/F");
  Book("puppiUZphi_JESTotalUp",&(puppiUZphi[1]),"puppiUZphi_JESTotalUp/F");
  Book("puppiUZphi_JESTotalDown",&(puppiUZphi[2]),"puppiUZphi_JESTotalDown/F");
  Book("puppiUAphi",&(puppiUAphi[0]),"puppiUAphi/F");
  Book("puppiUAphi_JESTotalUp",&(puppiUAphi[1]),"puppiUAphi_JESTotalUp/F");
  Book("puppiUAphi_JESTotalDown",&(puppiUAphi[2]),"puppiUAphi_JESTotalDown/F");
  Book("puppiUphi",&(puppiUphi[0]),"puppiUphi/F");
  Book("puppiUphi_JESTotalUp",&(puppiUphi[1]),"puppiUphi_JESTotalUp/F");
  Book("puppiUphi_JESTotalDown",&(puppiUphi[2]),"puppiUphi_JESTotalDown/F");
  Book("pfUWmag",&(pfUWmag[0]),"pfUWmag/F");
  Book("pfUWmag_JESTotalUp",&(pfUWmag[1]),"pfUWmag_JESTotalUp/F");
  Book("pfUWmag_JESTotalDown",&(pfUWmag[2]),"pfUWmag_JESTotalDown/F");
  Book("pfUZmag",&(pfUZmag[0]),"pfUZmag/F");
  Book("pfUZmag_JESTotalUp",&(pfUZmag[1]),"pfUZmag_JESTotalUp/F");
  Book("pfUZmag_JESTotalDown",&(pfUZmag[2]),"pfUZmag_JESTotalDown/F");
  Book("pfUAmag",&(pfUAmag[0]),"pfUAmag/F");
  Book("pfUAmag_JESTotalUp",&(pfUAmag[1]),"pfUAmag_JESTotalUp/F");
  Book("pfUAmag_JESTotalDown",&(pfUAmag[2]),"pfUAmag_JESTotalDown/F");
  Book("pfUmag",&(pfUmag[0]),"pfUmag/F");
  Book("pfUmag_JESTotalUp",&(pfUmag[1]),"pfUmag_JESTotalUp/F");
  Book("pfUmag_JESTotalDown",&(pfUmag[2]),"pfUmag_JESTotalDown/F");
  Book("pfUWphi",&(pfUWphi[0]),"pfUWphi/F");
  Book("pfUWphi_JESTotalUp",&(pfUWphi[1]),"pfUWphi_JESTotalUp/F");
  Book("pfUWphi_JESTotalDown",&(pfUWphi[2]),"pfUWphi_JESTotalDown/F");
  Book("pfUZphi",&(pfUZphi[0]),"pfUZphi/F");
  Book("pfUZphi_JESTotalUp",&(pfUZphi[1]),"pfUZphi_JESTotalUp/F");
  Book("pfUZphi_JESTotalDown",&(pfUZphi[2]),"pfUZphi_JESTotalDown/F");
  Book("pfUAphi",&(pfUAphi[0]),"pfUAphi/F");
  Book("pfUAphi_JESTotalUp",&(pfUAphi[1]),"pfUAphi_JESTotalUp/F");
  Book("pfUAphi_JESTotalDown",&(pfUAphi[2]),"pfUAphi_JESTotalDown/F");
  Book("pfUphi",&(pfUphi[0]),"pfUphi/F");
  Book("pfUphi_JESTotalUp",&(pfUphi[1]),"pfUphi_JESTotalUp/F");
  Book("pfUphi_JESTotalDown",&(pfUphi[2]),"pfUphi_JESTotalDown/F");
  Book("dphipfmet",&(dphipfmet[0]),"dphipfmet/F");
  Book("dphipfmet_JESTotalUp",&(dphipfmet[1]),"dphipfmet_JESTotalUp/F");
  Book("dphipfmet_JESTotalDown",&(dphipfmet[2]),"dphipfmet_JESTotalDown/F");
  Book("dphipuppimet",&(dphipuppimet[0]),"dphipuppimet/F");
  Book("dphipuppimet_JESTotalUp",&(dphipuppimet[1]),"dphipuppimet_JESTotalUp/F");
  Book("dphipuppimet_JESTotalDown",&(dphipuppimet[2]),"dphipuppimet_JESTotalDown/F");
  Book("dphipuppiUW",&(dphipuppiUW[0]),"dphipuppiUW/F");
  Book("dphipuppiUW_JESTotalUp",&(dphipuppiUW[1]),"dphipuppiUW_JESTotalUp/F");
  Book("dphipuppiUW_JESTotalDown",&(dphipuppiUW[2]),"dphipuppiUW_JESTotalDown/F");
  Book("dphipuppiUZ",&(dphipuppiUZ[0]),"dphipuppiUZ/F");
  Book("dphipuppiUZ_JESTotalUp",&(dphipuppiUZ[1]),"dphipuppiUZ_JESTotalUp/F");
  Book("dphipuppiUZ_JESTotalDown",&(dphipuppiUZ[2]),"dphipuppiUZ_JESTotalDown/F");
  Book("dphipuppiUA",&(dphipuppiUA[0]),"dphipuppiUA/F");
  Book("dphipuppiUA_JESTotalUp",&(dphipuppiUA[1]),"dphipuppiUA_JESTotalUp/F");
  Book("dphipuppiUA_JESTotalDown",&(dphipuppiUA[2]),"dphipuppiUA_JESTotalDown/F");
  Book("dphipfUW",&(dphipfUW[0]),"dphipfUW/F");
  Book("dphipfUW_JESTotalUp",&(dphipfUW[1]),"dphipfUW_JESTotalUp/F");
  Book("dphipfUW_JESTotalDown",&(dphipfUW[2]),"dphipfUW_JESTotalDown/F");
  Book("dphipfUZ",&(dphipfUZ[0]),"dphipfUZ/F");
  Book("dphipfUZ_JESTotalUp",&(dphipfUZ[1]),"dphipfUZ_JESTotalUp/F");
  Book("dphipfUZ_JESTotalDown",&(dphipfUZ[2]),"dphipfUZ_JESTotalDown/F");
  Book("dphipfUA",&(dphipfUA[0]),"dphipfUA/F");
  Book("dphipfUA_JESTotalUp",&(dphipfUA[1]),"dphipfUA_JESTotalUp/F");
  Book("dphipfUA_JESTotalDown",&(dphipfUA[2]),"dphipfUA_JESTotalDown/F");
  Book("dphipuppiU",&(dphipuppiU[0]),"dphipuppiU/F");
  Book("dphipuppiU_JESTotalUp",&(dphipuppiU[1]),"dphipuppiU_JESTotalUp/F");
  Book("dphipuppiU_JESTotalDown",&(dphipuppiU[2]),"dphipuppiU_JESTotalDown/F");
  Book("dphipfU",&(dphipfU[0]),"dphipfU/F");
  Book("dphipfU_JESTotalUp",&(dphipfU[1]),"dphipfU_JESTotalUp/F");
  Book("dphipfU_JESTotalDown",&(dphipfU[2]),"dphipfU_JESTotalDown/F");
  Book("trueGenBosonPt",&trueGenBosonPt,"trueGenBosonPt/F");
  Book("genBosonPt",&genBosonPt,"genBosonPt/F");
  Book("genBosonEta",&genBosonEta,"genBosonEta/F");
  Book("genBosonMass",&genBosonMass,"genBosonMass/F");
  Book("genBosonPhi",&genBosonPhi,"genBosonPhi/F");
  Book("genJet1Pt",&genJet1Pt,"genJet1Pt/F");
  Book("genJet2Pt",&genJet2Pt,"genJet2Pt/F");
  Book("genJet1Eta",&genJet1Eta,"genJet1Eta/F");
  Book("genJet2Eta",&genJet2Eta,"genJet2Eta/F");
  Book("genJet1Phi",&genJet1Phi,"genJet1Phi/F");
  Book("genJet2Phi",&genJet2Phi,"genJet2Phi/F");
  Book("SUEP_mult_pt",&(SUEP_mult_pt[0]),"SUEP_mult_pt/F");
  Book("SUEP_mult_pt_JESTotalUp",&(SUEP_mult_pt[1]),"SUEP_mult_pt_JESTotalUp/F");
  Book("SUEP_mult_pt_JESTotalDown",&(SUEP_mult_pt[2]),"SUEP_mult_pt_JESTotalDown/F");
  Book("SUEP_mult_m",&(SUEP_mult_m[0]),"SUEP_mult_m/F");
  Book("SUEP_mult_m_JESTotalUp",&(SUEP_mult_m[1]),"SUEP_mult_m_JESTotalUp/F");
  Book("SUEP_mult_m_JESTotalDown",&(SUEP_mult_m[2]),"SUEP_mult_m_JESTotalDown/F");
  Book("SUEP_mult_eta",&SUEP_mult_eta,"SUEP_mult_eta/F");
  Book("SUEP_mult_phi",&SUEP_mult_phi,"SUEP_mult_phi/F");
  Book("SUEP_mult_nconst",&SUEP_mult_nconst,"SUEP_mult_nconst/I");
  Book("SUEP_mult_spher",&SUEP_mult_spher,"SUEP_mult_spher/F");
  Book("SUEP_pt_pt",&(SUEP_pt_pt[0]),"SUEP_pt_pt/F");
  Book("SUEP_pt_pt_JESTotalUp",&(SUEP_pt_pt[1]),"SUEP_pt_pt_JESTotalUp/F");
  Book("SUEP_pt_pt_JESTotalDown",&(SUEP_pt_pt[2]),"SUEP_pt_pt_JESTotalDown/F");
  Book("SUEP_pt_m",&(SUEP_pt_m[0]),"SUEP_pt_m/F");
  Book("SUEP_pt_m_JESTotalUp",&(SUEP_pt_m[1]),"SUEP_pt_m_JESTotalUp/F");
  Book("SUEP_pt_m_JESTotalDown",&(SUEP_pt_m[2]),"SUEP_pt_m_JESTotalDown/F");
  Book("SUEP_pt_eta",&SUEP_pt_eta,"SUEP_pt_eta/F");
  Book("SUEP_pt_phi",&SUEP_pt_phi,"SUEP_pt_phi/F");
  Book("SUEP_pt_nconst",&SUEP_pt_nconst,"SUEP_pt_nconst/I");
  Book("SUEP_pt_spher",&SUEP_pt_spher,"SUEP_pt_spher/F");
  Book("SUEP_isr_pt",&SUEP_isr_pt,"SUEP_isr_pt/F");
  Book("SUEP_isr_m",&SUEP_isr_m,"SUEP_isr_m/F");
  Book("SUEP_isr_eta",&SUEP_isr_eta,"SUEP_isr_eta/F");
  Book("SUEP_isr_phi",&SUEP_isr_phi,"SUEP_isr_phi/F");
  Book("SUEP_isr_nconst",&SUEP_isr_nconst,"SUEP_isr_nconst/I");
  Book("SUEP_isr_spher",&SUEP_isr_spher,"SUEP_isr_spher/F");
  Book("nJet",&(nJet[0]),"nJet/I");
  Book("nJet_JESTotalUp",&(nJet[1]),"nJet_JESTotalUp/I");
  Book("nJet_JESTotalDown",&(nJet[2]),"nJet_JESTotalDown/I");
  Book("nJet_JESAbsoluteMPFBiasUp",&(nJet[3]),"nJet_JESAbsoluteMPFBiasUp/I");
  Book("nJet_JESAbsoluteMPFBiasDown",&(nJet[4]),"nJet_JESAbsoluteMPFBiasDown/I");
  Book("nJet_JESAbsoluteScaleUp",&(nJet[5]),"nJet_JESAbsoluteScaleUp/I");
  Book("nJet_JESAbsoluteScaleDown",&(nJet[6]),"nJet_JESAbsoluteScaleDown/I");
  Book("nJet_JESAbsoluteStatUp",&(nJet[7]),"nJet_JESAbsoluteStatUp/I");
  Book("nJet_JESAbsoluteStatDown",&(nJet[8]),"nJet_JESAbsoluteStatDown/I");
  Book("nJet_JESFlavorQCDUp",&(nJet[9]),"nJet_JESFlavorQCDUp/I");
  Book("nJet_JESFlavorQCDDown",&(nJet[10]),"nJet_JESFlavorQCDDown/I");
  Book("nJet_JESFragmentationUp",&(nJet[11]),"nJet_JESFragmentationUp/I");
  Book("nJet_JESFragmentationDown",&(nJet[12]),"nJet_JESFragmentationDown/I");
  Book("nJet_JESPileUpDataMCUp",&(nJet[13]),"nJet_JESPileUpDataMCUp/I");
  Book("nJet_JESPileUpDataMCDown",&(nJet[14]),"nJet_JESPileUpDataMCDown/I");
  Book("nJet_JESPileUpPtBBUp",&(nJet[15]),"nJet_JESPileUpPtBBUp/I");
  Book("nJet_JESPileUpPtBBDown",&(nJet[16]),"nJet_JESPileUpPtBBDown/I");
  Book("nJet_JESPileUpPtEC1Up",&(nJet[17]),"nJet_JESPileUpPtEC1Up/I");
  Book("nJet_JESPileUpPtEC1Down",&(nJet[18]),"nJet_JESPileUpPtEC1Down/I");
  Book("nJet_JESPileUpPtEC2Up",&(nJet[19]),"nJet_JESPileUpPtEC2Up/I");
  Book("nJet_JESPileUpPtEC2Down",&(nJet[20]),"nJet_JESPileUpPtEC2Down/I");
  Book("nJet_JESPileUpPtRefUp",&(nJet[21]),"nJet_JESPileUpPtRefUp/I");
  Book("nJet_JESPileUpPtRefDown",&(nJet[22]),"nJet_JESPileUpPtRefDown/I");
  Book("nJet_JESRelativeFSRUp",&(nJet[23]),"nJet_JESRelativeFSRUp/I");
  Book("nJet_JESRelativeFSRDown",&(nJet[24]),"nJet_JESRelativeFSRDown/I");
  Book("nJet_JESRelativeJEREC1Up",&(nJet[25]),"nJet_JESRelativeJEREC1Up/I");
  Book("nJet_JESRelativeJEREC1Down",&(nJet[26]),"nJet_JESRelativeJEREC1Down/I");
  Book("nJet_JESRelativePtBBUp",&(nJet[27]),"nJet_JESRelativePtBBUp/I");
  Book("nJet_JESRelativePtBBDown",&(nJet[28]),"nJet_JESRelativePtBBDown/I");
  Book("nJet_JESRelativePtEC1Up",&(nJet[29]),"nJet_JESRelativePtEC1Up/I");
  Book("nJet_JESRelativePtEC1Down",&(nJet[30]),"nJet_JESRelativePtEC1Down/I");
  Book("nJet_JESRelativePtEC2Up",&(nJet[31]),"nJet_JESRelativePtEC2Up/I");
  Book("nJet_JESRelativePtEC2Down",&(nJet[32]),"nJet_JESRelativePtEC2Down/I");
  Book("nJet_JESRelativeStatECUp",&(nJet[33]),"nJet_JESRelativeStatECUp/I");
  Book("nJet_JESRelativeStatECDown",&(nJet[34]),"nJet_JESRelativeStatECDown/I");
  Book("nJet_JESRelativeStatFSRUp",&(nJet[35]),"nJet_JESRelativeStatFSRUp/I");
  Book("nJet_JESRelativeStatFSRDown",&(nJet[36]),"nJet_JESRelativeStatFSRDown/I");
  Book("nJet_JESSinglePionECALUp",&(nJet[37]),"nJet_JESSinglePionECALUp/I");
  Book("nJet_JESSinglePionECALDown",&(nJet[38]),"nJet_JESSinglePionECALDown/I");
  Book("nJet_JESSinglePionHCALUp",&(nJet[39]),"nJet_JESSinglePionHCALUp/I");
  Book("nJet_JESSinglePionHCALDown",&(nJet[40]),"nJet_JESSinglePionHCALDown/I");
  Book("nJet_JESTimePtEtaUp",&(nJet[41]),"nJet_JESTimePtEtaUp/I");
  Book("nJet_JESTimePtEtaDown",&(nJet[42]),"nJet_JESTimePtEtaDown/I");
  Book("nJetMax",&nJetMax,"nJetMax/I");
  Book("nIsoJet",&(nIsoJet[0]),"nIsoJet/I");
  Book("nIsoJet_JESTotalUp",&(nIsoJet[1]),"nIsoJet_JESTotalUp/I");
  Book("nIsoJet_JESTotalDown",&(nIsoJet[2]),"nIsoJet_JESTotalDown/I");
  Book("nIsoJet_JESAbsoluteMPFBiasUp",&(nIsoJet[3]),"nIsoJet_JESAbsoluteMPFBiasUp/I");
  Book("nIsoJet_JESAbsoluteMPFBiasDown",&(nIsoJet[4]),"nIsoJet_JESAbsoluteMPFBiasDown/I");
  Book("nIsoJet_JESAbsoluteScaleUp",&(nIsoJet[5]),"nIsoJet_JESAbsoluteScaleUp/I");
  Book("nIsoJet_JESAbsoluteScaleDown",&(nIsoJet[6]),"nIsoJet_JESAbsoluteScaleDown/I");
  Book("nIsoJet_JESAbsoluteStatUp",&(nIsoJet[7]),"nIsoJet_JESAbsoluteStatUp/I");
  Book("nIsoJet_JESAbsoluteStatDown",&(nIsoJet[8]),"nIsoJet_JESAbsoluteStatDown/I");
  Book("nIsoJet_JESFlavorQCDUp",&(nIsoJet[9]),"nIsoJet_JESFlavorQCDUp/I");
  Book("nIsoJet_JESFlavorQCDDown",&(nIsoJet[10]),"nIsoJet_JESFlavorQCDDown/I");
  Book("nIsoJet_JESFragmentationUp",&(nIsoJet[11]),"nIsoJet_JESFragmentationUp/I");
  Book("nIsoJet_JESFragmentationDown",&(nIsoJet[12]),"nIsoJet_JESFragmentationDown/I");
  Book("nIsoJet_JESPileUpDataMCUp",&(nIsoJet[13]),"nIsoJet_JESPileUpDataMCUp/I");
  Book("nIsoJet_JESPileUpDataMCDown",&(nIsoJet[14]),"nIsoJet_JESPileUpDataMCDown/I");
  Book("nIsoJet_JESPileUpPtBBUp",&(nIsoJet[15]),"nIsoJet_JESPileUpPtBBUp/I");
  Book("nIsoJet_JESPileUpPtBBDown",&(nIsoJet[16]),"nIsoJet_JESPileUpPtBBDown/I");
  Book("nIsoJet_JESPileUpPtEC1Up",&(nIsoJet[17]),"nIsoJet_JESPileUpPtEC1Up/I");
  Book("nIsoJet_JESPileUpPtEC1Down",&(nIsoJet[18]),"nIsoJet_JESPileUpPtEC1Down/I");
  Book("nIsoJet_JESPileUpPtEC2Up",&(nIsoJet[19]),"nIsoJet_JESPileUpPtEC2Up/I");
  Book("nIsoJet_JESPileUpPtEC2Down",&(nIsoJet[20]),"nIsoJet_JESPileUpPtEC2Down/I");
  Book("nIsoJet_JESPileUpPtRefUp",&(nIsoJet[21]),"nIsoJet_JESPileUpPtRefUp/I");
  Book("nIsoJet_JESPileUpPtRefDown",&(nIsoJet[22]),"nIsoJet_JESPileUpPtRefDown/I");
  Book("nIsoJet_JESRelativeFSRUp",&(nIsoJet[23]),"nIsoJet_JESRelativeFSRUp/I");
  Book("nIsoJet_JESRelativeFSRDown",&(nIsoJet[24]),"nIsoJet_JESRelativeFSRDown/I");
  Book("nIsoJet_JESRelativeJEREC1Up",&(nIsoJet[25]),"nIsoJet_JESRelativeJEREC1Up/I");
  Book("nIsoJet_JESRelativeJEREC1Down",&(nIsoJet[26]),"nIsoJet_JESRelativeJEREC1Down/I");
  Book("nIsoJet_JESRelativePtBBUp",&(nIsoJet[27]),"nIsoJet_JESRelativePtBBUp/I");
  Book("nIsoJet_JESRelativePtBBDown",&(nIsoJet[28]),"nIsoJet_JESRelativePtBBDown/I");
  Book("nIsoJet_JESRelativePtEC1Up",&(nIsoJet[29]),"nIsoJet_JESRelativePtEC1Up/I");
  Book("nIsoJet_JESRelativePtEC1Down",&(nIsoJet[30]),"nIsoJet_JESRelativePtEC1Down/I");
  Book("nIsoJet_JESRelativePtEC2Up",&(nIsoJet[31]),"nIsoJet_JESRelativePtEC2Up/I");
  Book("nIsoJet_JESRelativePtEC2Down",&(nIsoJet[32]),"nIsoJet_JESRelativePtEC2Down/I");
  Book("nIsoJet_JESRelativeStatECUp",&(nIsoJet[33]),"nIsoJet_JESRelativeStatECUp/I");
  Book("nIsoJet_JESRelativeStatECDown",&(nIsoJet[34]),"nIsoJet_JESRelativeStatECDown/I");
  Book("nIsoJet_JESRelativeStatFSRUp",&(nIsoJet[35]),"nIsoJet_JESRelativeStatFSRUp/I");
  Book("nIsoJet_JESRelativeStatFSRDown",&(nIsoJet[36]),"nIsoJet_JESRelativeStatFSRDown/I");
  Book("nIsoJet_JESSinglePionECALUp",&(nIsoJet[37]),"nIsoJet_JESSinglePionECALUp/I");
  Book("nIsoJet_JESSinglePionECALDown",&(nIsoJet[38]),"nIsoJet_JESSinglePionECALDown/I");
  Book("nIsoJet_JESSinglePionHCALUp",&(nIsoJet[39]),"nIsoJet_JESSinglePionHCALUp/I");
  Book("nIsoJet_JESSinglePionHCALDown",&(nIsoJet[40]),"nIsoJet_JESSinglePionHCALDown/I");
  Book("nIsoJet_JESTimePtEtaUp",&(nIsoJet[41]),"nIsoJet_JESTimePtEtaUp/I");
  Book("nIsoJet_JESTimePtEtaDown",&(nIsoJet[42]),"nIsoJet_JESTimePtEtaDown/I");
  Book("jetht",&(jetht[0]),"jetht/F");
  Book("jetht_JESTotalUp",&(jetht[1]),"jetht_JESTotalUp/F");
  Book("jetht_JESTotalDown",&(jetht[2]),"jetht_JESTotalDown/F");
  Book("jetht_JESAbsoluteMPFBiasUp",&(jetht[3]),"jetht_JESAbsoluteMPFBiasUp/F");
  Book("jetht_JESAbsoluteMPFBiasDown",&(jetht[4]),"jetht_JESAbsoluteMPFBiasDown/F");
  Book("jetht_JESAbsoluteScaleUp",&(jetht[5]),"jetht_JESAbsoluteScaleUp/F");
  Book("jetht_JESAbsoluteScaleDown",&(jetht[6]),"jetht_JESAbsoluteScaleDown/F");
  Book("jetht_JESAbsoluteStatUp",&(jetht[7]),"jetht_JESAbsoluteStatUp/F");
  Book("jetht_JESAbsoluteStatDown",&(jetht[8]),"jetht_JESAbsoluteStatDown/F");
  Book("jetht_JESFlavorQCDUp",&(jetht[9]),"jetht_JESFlavorQCDUp/F");
  Book("jetht_JESFlavorQCDDown",&(jetht[10]),"jetht_JESFlavorQCDDown/F");
  Book("jetht_JESFragmentationUp",&(jetht[11]),"jetht_JESFragmentationUp/F");
  Book("jetht_JESFragmentationDown",&(jetht[12]),"jetht_JESFragmentationDown/F");
  Book("jetht_JESPileUpDataMCUp",&(jetht[13]),"jetht_JESPileUpDataMCUp/F");
  Book("jetht_JESPileUpDataMCDown",&(jetht[14]),"jetht_JESPileUpDataMCDown/F");
  Book("jetht_JESPileUpPtBBUp",&(jetht[15]),"jetht_JESPileUpPtBBUp/F");
  Book("jetht_JESPileUpPtBBDown",&(jetht[16]),"jetht_JESPileUpPtBBDown/F");
  Book("jetht_JESPileUpPtEC1Up",&(jetht[17]),"jetht_JESPileUpPtEC1Up/F");
  Book("jetht_JESPileUpPtEC1Down",&(jetht[18]),"jetht_JESPileUpPtEC1Down/F");
  Book("jetht_JESPileUpPtEC2Up",&(jetht[19]),"jetht_JESPileUpPtEC2Up/F");
  Book("jetht_JESPileUpPtEC2Down",&(jetht[20]),"jetht_JESPileUpPtEC2Down/F");
  Book("jetht_JESPileUpPtRefUp",&(jetht[21]),"jetht_JESPileUpPtRefUp/F");
  Book("jetht_JESPileUpPtRefDown",&(jetht[22]),"jetht_JESPileUpPtRefDown/F");
  Book("jetht_JESRelativeFSRUp",&(jetht[23]),"jetht_JESRelativeFSRUp/F");
  Book("jetht_JESRelativeFSRDown",&(jetht[24]),"jetht_JESRelativeFSRDown/F");
  Book("jetht_JESRelativeJEREC1Up",&(jetht[25]),"jetht_JESRelativeJEREC1Up/F");
  Book("jetht_JESRelativeJEREC1Down",&(jetht[26]),"jetht_JESRelativeJEREC1Down/F");
  Book("jetht_JESRelativePtBBUp",&(jetht[27]),"jetht_JESRelativePtBBUp/F");
  Book("jetht_JESRelativePtBBDown",&(jetht[28]),"jetht_JESRelativePtBBDown/F");
  Book("jetht_JESRelativePtEC1Up",&(jetht[29]),"jetht_JESRelativePtEC1Up/F");
  Book("jetht_JESRelativePtEC1Down",&(jetht[30]),"jetht_JESRelativePtEC1Down/F");
  Book("jetht_JESRelativePtEC2Up",&(jetht[31]),"jetht_JESRelativePtEC2Up/F");
  Book("jetht_JESRelativePtEC2Down",&(jetht[32]),"jetht_JESRelativePtEC2Down/F");
  Book("jetht_JESRelativeStatECUp",&(jetht[33]),"jetht_JESRelativeStatECUp/F");
  Book("jetht_JESRelativeStatECDown",&(jetht[34]),"jetht_JESRelativeStatECDown/F");
  Book("jetht_JESRelativeStatFSRUp",&(jetht[35]),"jetht_JESRelativeStatFSRUp/F");
  Book("jetht_JESRelativeStatFSRDown",&(jetht[36]),"jetht_JESRelativeStatFSRDown/F");
  Book("jetht_JESSinglePionECALUp",&(jetht[37]),"jetht_JESSinglePionECALUp/F");
  Book("jetht_JESSinglePionECALDown",&(jetht[38]),"jetht_JESSinglePionECALDown/F");
  Book("jetht_JESSinglePionHCALUp",&(jetht[39]),"jetht_JESSinglePionHCALUp/F");
  Book("jetht_JESSinglePionHCALDown",&(jetht[40]),"jetht_JESSinglePionHCALDown/F");
  Book("jetht_JESTimePtEtaUp",&(jetht[41]),"jetht_JESTimePtEtaUp/F");
  Book("jetht_JESTimePtEtaDown",&(jetht[42]),"jetht_JESTimePtEtaDown/F");
  Book("jetPt",jetPt[0],"jetPt["+TString("nJetMax")+"]/F");
  Book("jetPt_JESTotalUp",jetPt[1],"jetPt_JESTotalUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESTotalDown",jetPt[2],"jetPt_JESTotalDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESAbsoluteMPFBiasUp",jetPt[3],"jetPt_JESAbsoluteMPFBiasUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESAbsoluteMPFBiasDown",jetPt[4],"jetPt_JESAbsoluteMPFBiasDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESAbsoluteScaleUp",jetPt[5],"jetPt_JESAbsoluteScaleUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESAbsoluteScaleDown",jetPt[6],"jetPt_JESAbsoluteScaleDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESAbsoluteStatUp",jetPt[7],"jetPt_JESAbsoluteStatUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESAbsoluteStatDown",jetPt[8],"jetPt_JESAbsoluteStatDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESFlavorQCDUp",jetPt[9],"jetPt_JESFlavorQCDUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESFlavorQCDDown",jetPt[10],"jetPt_JESFlavorQCDDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESFragmentationUp",jetPt[11],"jetPt_JESFragmentationUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESFragmentationDown",jetPt[12],"jetPt_JESFragmentationDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpDataMCUp",jetPt[13],"jetPt_JESPileUpDataMCUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpDataMCDown",jetPt[14],"jetPt_JESPileUpDataMCDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtBBUp",jetPt[15],"jetPt_JESPileUpPtBBUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtBBDown",jetPt[16],"jetPt_JESPileUpPtBBDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtEC1Up",jetPt[17],"jetPt_JESPileUpPtEC1Up["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtEC1Down",jetPt[18],"jetPt_JESPileUpPtEC1Down["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtEC2Up",jetPt[19],"jetPt_JESPileUpPtEC2Up["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtEC2Down",jetPt[20],"jetPt_JESPileUpPtEC2Down["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtRefUp",jetPt[21],"jetPt_JESPileUpPtRefUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtRefDown",jetPt[22],"jetPt_JESPileUpPtRefDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeFSRUp",jetPt[23],"jetPt_JESRelativeFSRUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeFSRDown",jetPt[24],"jetPt_JESRelativeFSRDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeJEREC1Up",jetPt[25],"jetPt_JESRelativeJEREC1Up["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeJEREC1Down",jetPt[26],"jetPt_JESRelativeJEREC1Down["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativePtBBUp",jetPt[27],"jetPt_JESRelativePtBBUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativePtBBDown",jetPt[28],"jetPt_JESRelativePtBBDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativePtEC1Up",jetPt[29],"jetPt_JESRelativePtEC1Up["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativePtEC1Down",jetPt[30],"jetPt_JESRelativePtEC1Down["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativePtEC2Up",jetPt[31],"jetPt_JESRelativePtEC2Up["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativePtEC2Down",jetPt[32],"jetPt_JESRelativePtEC2Down["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeStatECUp",jetPt[33],"jetPt_JESRelativeStatECUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeStatECDown",jetPt[34],"jetPt_JESRelativeStatECDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeStatFSRUp",jetPt[35],"jetPt_JESRelativeStatFSRUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeStatFSRDown",jetPt[36],"jetPt_JESRelativeStatFSRDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESSinglePionECALUp",jetPt[37],"jetPt_JESSinglePionECALUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESSinglePionECALDown",jetPt[38],"jetPt_JESSinglePionECALDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESSinglePionHCALUp",jetPt[39],"jetPt_JESSinglePionHCALUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESSinglePionHCALDown",jetPt[40],"jetPt_JESSinglePionHCALDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESTimePtEtaUp",jetPt[41],"jetPt_JESTimePtEtaUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESTimePtEtaDown",jetPt[42],"jetPt_JESTimePtEtaDown["+TString("nJetMax")+"]/F");
  Book("jetM",jetM[0],"jetM["+TString("nJetMax")+"]/F");
  Book("jetM_JESTotalUp",jetM[1],"jetM_JESTotalUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESTotalDown",jetM[2],"jetM_JESTotalDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESAbsoluteMPFBiasUp",jetM[3],"jetM_JESAbsoluteMPFBiasUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESAbsoluteMPFBiasDown",jetM[4],"jetM_JESAbsoluteMPFBiasDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESAbsoluteScaleUp",jetM[5],"jetM_JESAbsoluteScaleUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESAbsoluteScaleDown",jetM[6],"jetM_JESAbsoluteScaleDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESAbsoluteStatUp",jetM[7],"jetM_JESAbsoluteStatUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESAbsoluteStatDown",jetM[8],"jetM_JESAbsoluteStatDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESFlavorQCDUp",jetM[9],"jetM_JESFlavorQCDUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESFlavorQCDDown",jetM[10],"jetM_JESFlavorQCDDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESFragmentationUp",jetM[11],"jetM_JESFragmentationUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESFragmentationDown",jetM[12],"jetM_JESFragmentationDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESPileUpDataMCUp",jetM[13],"jetM_JESPileUpDataMCUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESPileUpDataMCDown",jetM[14],"jetM_JESPileUpDataMCDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESPileUpPtBBUp",jetM[15],"jetM_JESPileUpPtBBUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESPileUpPtBBDown",jetM[16],"jetM_JESPileUpPtBBDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESPileUpPtEC1Up",jetM[17],"jetM_JESPileUpPtEC1Up["+TString("nJetMax")+"]/F");
  Book("jetM_JESPileUpPtEC1Down",jetM[18],"jetM_JESPileUpPtEC1Down["+TString("nJetMax")+"]/F");
  Book("jetM_JESPileUpPtEC2Up",jetM[19],"jetM_JESPileUpPtEC2Up["+TString("nJetMax")+"]/F");
  Book("jetM_JESPileUpPtEC2Down",jetM[20],"jetM_JESPileUpPtEC2Down["+TString("nJetMax")+"]/F");
  Book("jetM_JESPileUpPtRefUp",jetM[21],"jetM_JESPileUpPtRefUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESPileUpPtRefDown",jetM[22],"jetM_JESPileUpPtRefDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativeFSRUp",jetM[23],"jetM_JESRelativeFSRUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativeFSRDown",jetM[24],"jetM_JESRelativeFSRDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativeJEREC1Up",jetM[25],"jetM_JESRelativeJEREC1Up["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativeJEREC1Down",jetM[26],"jetM_JESRelativeJEREC1Down["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativePtBBUp",jetM[27],"jetM_JESRelativePtBBUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativePtBBDown",jetM[28],"jetM_JESRelativePtBBDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativePtEC1Up",jetM[29],"jetM_JESRelativePtEC1Up["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativePtEC1Down",jetM[30],"jetM_JESRelativePtEC1Down["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativePtEC2Up",jetM[31],"jetM_JESRelativePtEC2Up["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativePtEC2Down",jetM[32],"jetM_JESRelativePtEC2Down["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativeStatECUp",jetM[33],"jetM_JESRelativeStatECUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativeStatECDown",jetM[34],"jetM_JESRelativeStatECDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativeStatFSRUp",jetM[35],"jetM_JESRelativeStatFSRUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESRelativeStatFSRDown",jetM[36],"jetM_JESRelativeStatFSRDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESSinglePionECALUp",jetM[37],"jetM_JESSinglePionECALUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESSinglePionECALDown",jetM[38],"jetM_JESSinglePionECALDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESSinglePionHCALUp",jetM[39],"jetM_JESSinglePionHCALUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESSinglePionHCALDown",jetM[40],"jetM_JESSinglePionHCALDown["+TString("nJetMax")+"]/F");
  Book("jetM_JESTimePtEtaUp",jetM[41],"jetM_JESTimePtEtaUp["+TString("nJetMax")+"]/F");
  Book("jetM_JESTimePtEtaDown",jetM[42],"jetM_JESTimePtEtaDown["+TString("nJetMax")+"]/F");
  Book("jetEta",jetEta,"jetEta["+TString("nJetMax")+"]/F");
  Book("jetPhi",jetPhi,"jetPhi["+TString("nJetMax")+"]/F");
  Book("jetGenPt",jetGenPt,"jetGenPt["+TString("nJetMax")+"]/F");
  Book("jetIsTight",jetIsTight,"jetIsTight["+TString("nJetMax")+"]/I");
  Book("jetIsIso",jetIsIso,"jetIsIso["+TString("nJetMax")+"]/I");
  Book("nTrk",&nTrk,"nTrk/I");
  Book("trkPt",trkPt,"trkPt["+TString("nTrk")+"]/F");
  Book("trkEta",trkEta,"trkEta["+TString("nTrk")+"]/F");
  Book("trkPhi",trkPhi,"trkPhi["+TString("nTrk")+"]/F");
  Book("nHF",&nHF,"nHF/I");
  Book("nB",&nB,"nB/I");
  Book("nBGenJets",&nBGenJets,"nBGenJets/I");
  Book("nStatus2BHadrons",&nStatus2BHadrons,"nStatus2BHadrons/I");
  Book("genFatJetPt",&genFatJetPt,"genFatJetPt/F");
  Book("genFatJetNProngs",&genFatJetNProngs,"genFatJetNProngs/I");
  Book("nGenJet",&nGenJet,"nGenJet/I");
  Book("GenJetPt",GenJetPt,"GenJetPt["+TString("nGenJet")+"]/F");
  Book("GenJetEta",GenJetEta,"GenJetEta["+TString("nGenJet")+"]/F");
  Book("GenJetPhi",GenJetPhi,"GenJetPhi["+TString("nGenJet")+"]/F");
  Book("nLoosePhoton",&nLoosePhoton,"nLoosePhoton/I");
  Book("nTightPhoton",&nTightPhoton,"nTightPhoton/I");
  Book("loosePho1IsTight",&loosePho1IsTight,"loosePho1IsTight/I");
  Book("loosePho1Pt",&loosePho1Pt,"loosePho1Pt/F");
  Book("loosePho1Eta",&loosePho1Eta,"loosePho1Eta/F");
  Book("loosePho1Phi",&loosePho1Phi,"loosePho1Phi/F");
  Book("loosePho1r9",&loosePho1r9,"loosePho1r9/F");
  Book("loosePho1chIso",&loosePho1chIso,"loosePho1chIso/F");
  Book("loosePho1nhIso",&loosePho1nhIso,"loosePho1nhIso/F");
  Book("loosePho1phIso",&loosePho1phIso,"loosePho1phIso/F");
  Book("loosePho1hOverE",&loosePho1hOverE,"loosePho1hOverE/F");
  Book("loosePho1sieie",&loosePho1sieie,"loosePho1sieie/F");
  Book("loosePho1SelBit",&loosePho1SelBit,"loosePho1SelBit/I");
  Book("looseGenPho1PdgId",&looseGenPho1PdgId,"looseGenPho1PdgId/I");
  Book("loosePhoeveto",&loosePhoeveto,"loosePhoeveto/I");
  Book("nFakePhoton",&nFakePhoton,"nFakePhoton/I");
  Book("FakePho1Pt",&FakePho1Pt,"FakePho1Pt/F");
  Book("FakePho1Eta",&FakePho1Eta,"FakePho1Eta/F");
  Book("FakePho1Phi",&FakePho1Phi,"FakePho1Phi/F");
  Book("genPhotonPt",&genPhotonPt,"genPhotonPt/F");
  Book("genPhotonEta",&genPhotonEta,"genPhotonEta/F");
  Book("genPhotonPhi",&genPhotonPhi,"genPhotonPhi/F");
  Book("nLooseLep",&nLooseLep,"nLooseLep/I");
  Book("nLooseElectron",&nLooseElectron,"nLooseElectron/I");
  Book("nLooseMuon",&nLooseMuon,"nLooseMuon/I");
  Book("nTightLep",&nTightLep,"nTightLep/I");
  Book("nTightElectron",&nTightElectron,"nTightElectron/I");
  Book("nTightMuon",&nTightMuon,"nTightMuon/I");
  Book("muonPt",muonPt,"muonPt["+TString("nLooseMuon")+"]/F");
  Book("muonEta",muonEta,"muonEta["+TString("nLooseMuon")+"]/F");
  Book("muonPhi",muonPhi,"muonPhi["+TString("nLooseMuon")+"]/F");
  Book("muonSelBit",muonSelBit,"muonSelBit["+TString("nLooseMuon")+"]/I");
  Book("muonPdgId",muonPdgId,"muonPdgId["+TString("nLooseMuon")+"]/I");
  Book("muonD0",muonD0,"muonD0["+TString("nLooseMuon")+"]/F");
  Book("muonDZ",muonDZ,"muonDZ["+TString("nLooseMuon")+"]/F");
  Book("muonIsSoftMuon",muonIsSoftMuon,"muonIsSoftMuon["+TString("nLooseMuon")+"]/I");
  Book("muonCombIso",muonCombIso,"muonCombIso["+TString("nLooseMuon")+"]/F");
  Book("muonSfLoose",muonSfLoose,"muonSfLoose["+TString("nLooseMuon")+"]/F");
  Book("muonSfMedium",muonSfMedium,"muonSfMedium["+TString("nLooseMuon")+"]/F");
  Book("muonSfTight",muonSfTight,"muonSfTight["+TString("nLooseMuon")+"]/F");
  Book("muonSfUnc",muonSfUnc,"muonSfUnc["+TString("nLooseMuon")+"]/F");
  Book("muonSfReco",muonSfReco,"muonSfReco["+TString("nLooseMuon")+"]/F");
  Book("muTrigMatch",muTrigMatch,"muTrigMatch["+TString("nLooseMuon")+"]/I");
  Book("electronPt",electronPt,"electronPt["+TString("nLooseElectron")+"]/F");
  Book("electronEta",electronEta,"electronEta["+TString("nLooseElectron")+"]/F");
  Book("electronPhi",electronPhi,"electronPhi["+TString("nLooseElectron")+"]/F");
  Book("electronSelBit",electronSelBit,"electronSelBit["+TString("nLooseElectron")+"]/I");
  Book("electronPdgId",electronPdgId,"electronPdgId["+TString("nLooseElectron")+"]/I");
  Book("electronPhoMatch",electronPhoMatch,"electronPhoMatch["+TString("nLooseElectron")+"]/I");
  Book("electronLPhoMatch",electronLPhoMatch,"electronLPhoMatch["+TString("nLooseElectron")+"]/I");
  Book("electronSfLoose",electronSfLoose,"electronSfLoose["+TString("nLooseElectron")+"]/F");
  Book("electronSfMedium",electronSfMedium,"electronSfMedium["+TString("nLooseElectron")+"]/F");
  Book("electronSfTight",electronSfTight,"electronSfTight["+TString("nLooseElectron")+"]/F");
  Book("electronSfUnc",electronSfUnc,"electronSfUnc["+TString("nLooseElectron")+"]/F");
  Book("electronSfReco",electronSfReco,"electronSfReco["+TString("nLooseElectron")+"]/F");
  Book("electronSfMvaWP90",electronSfMvaWP90,"electronSfMvaWP90["+TString("nLooseElectron")+"]/F");
  Book("electronSfMvaWP80",electronSfMvaWP80,"electronSfMvaWP80["+TString("nLooseElectron")+"]/F");
  Book("electronD0",electronD0,"electronD0["+TString("nLooseElectron")+"]/F");
  Book("electronDZ",electronDZ,"electronDZ["+TString("nLooseElectron")+"]/F");
  Book("electronNMissingHits",electronNMissingHits,"electronNMissingHits["+TString("nLooseElectron")+"]/I");
  Book("electronTripleCharge",electronTripleCharge,"electronTripleCharge["+TString("nLooseElectron")+"]/I");
  Book("electronCombIso",electronCombIso,"electronCombIso["+TString("nLooseElectron")+"]/F");
  Book("eleTrigMatch",eleTrigMatch,"eleTrigMatch["+TString("nLooseElectron")+"]/I");
  Book("diLepMass",&diLepMass,"diLepMass/F");
  Book("nTau",&nTau,"nTau/I");
  Book("mT",&(mT[0]),"mT/F");
  Book("mT_JESTotalUp",&(mT[1]),"mT_JESTotalUp/F");
  Book("mT_JESTotalDown",&(mT[2]),"mT_JESTotalDown/F");
  Book("tauPt",tauPt,"tauPt["+TString("nTau")+"]/F");
  Book("tauEta",tauEta,"tauEta["+TString("nTau")+"]/F");
  Book("tauPhi",tauPhi,"tauPhi["+TString("nTau")+"]/F");
  Book("scaleUp",&scaleUp,"scaleUp/F");
  Book("scaleDown",&scaleDown,"scaleDown/F");
  Book("pdfUp",&pdfUp,"pdfUp/F");
  Book("pdfDown",&pdfDown,"pdfDown/F");
  Book("scale",scale,"scale["+TString("6")+"]/F");
  Book("lheHT",&lheHT,"lheHT/F");
  Book("lheNjets",&lheNjets,"lheNjets/I");
  Book("isGS",&isGS,"isGS/I");
  if (is_adv) {
    Book("hbbconstpt",hbbconstpt,"hbbconstpt["+TString("200")+"]/F");
    Book("hbbconsteta",hbbconsteta,"hbbconsteta["+TString("200")+"]/F");
    Book("hbbconstphi",hbbconstphi,"hbbconstphi["+TString("200")+"]/F");
    Book("hbbconste",hbbconste,"hbbconste["+TString("200")+"]/F");
    Book("hbbconstid",hbbconstid,"hbbconstid["+TString("200")+"]/I");
  }
  if (is_fatjet) {
    Book("nFatJet",&nFatJet,"nFatJet/I");
    Book("nFatJetTrunc",&nFatJetTrunc,"nFatJetTrunc/I");
    Book("fjTau32",fjTau32,"fjTau32["+TString("nFatJetTrunc")+"]/F");
    Book("fjTau21",fjTau21,"fjTau21["+TString("nFatJetTrunc")+"]/F");
    Book("fjTau32SD",fjTau32SD,"fjTau32SD["+TString("nFatJetTrunc")+"]/F");
    Book("fjTau21SD",fjTau21SD,"fjTau21SD["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD",fjMSD[0],"fjMSD["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESTotalUp",fjMSD[1],"fjMSD_JESTotalUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESTotalDown",fjMSD[2],"fjMSD_JESTotalDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESAbsoluteMPFBiasUp",fjMSD[3],"fjMSD_JESAbsoluteMPFBiasUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESAbsoluteMPFBiasDown",fjMSD[4],"fjMSD_JESAbsoluteMPFBiasDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESAbsoluteScaleUp",fjMSD[5],"fjMSD_JESAbsoluteScaleUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESAbsoluteScaleDown",fjMSD[6],"fjMSD_JESAbsoluteScaleDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESAbsoluteStatUp",fjMSD[7],"fjMSD_JESAbsoluteStatUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESAbsoluteStatDown",fjMSD[8],"fjMSD_JESAbsoluteStatDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESFlavorQCDUp",fjMSD[9],"fjMSD_JESFlavorQCDUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESFlavorQCDDown",fjMSD[10],"fjMSD_JESFlavorQCDDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESFragmentationUp",fjMSD[11],"fjMSD_JESFragmentationUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESFragmentationDown",fjMSD[12],"fjMSD_JESFragmentationDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESPileUpDataMCUp",fjMSD[13],"fjMSD_JESPileUpDataMCUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESPileUpDataMCDown",fjMSD[14],"fjMSD_JESPileUpDataMCDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESPileUpPtBBUp",fjMSD[15],"fjMSD_JESPileUpPtBBUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESPileUpPtBBDown",fjMSD[16],"fjMSD_JESPileUpPtBBDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESPileUpPtEC1Up",fjMSD[17],"fjMSD_JESPileUpPtEC1Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESPileUpPtEC1Down",fjMSD[18],"fjMSD_JESPileUpPtEC1Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESPileUpPtEC2Up",fjMSD[19],"fjMSD_JESPileUpPtEC2Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESPileUpPtEC2Down",fjMSD[20],"fjMSD_JESPileUpPtEC2Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESPileUpPtRefUp",fjMSD[21],"fjMSD_JESPileUpPtRefUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESPileUpPtRefDown",fjMSD[22],"fjMSD_JESPileUpPtRefDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativeFSRUp",fjMSD[23],"fjMSD_JESRelativeFSRUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativeFSRDown",fjMSD[24],"fjMSD_JESRelativeFSRDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativeJEREC1Up",fjMSD[25],"fjMSD_JESRelativeJEREC1Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativeJEREC1Down",fjMSD[26],"fjMSD_JESRelativeJEREC1Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativePtBBUp",fjMSD[27],"fjMSD_JESRelativePtBBUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativePtBBDown",fjMSD[28],"fjMSD_JESRelativePtBBDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativePtEC1Up",fjMSD[29],"fjMSD_JESRelativePtEC1Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativePtEC1Down",fjMSD[30],"fjMSD_JESRelativePtEC1Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativePtEC2Up",fjMSD[31],"fjMSD_JESRelativePtEC2Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativePtEC2Down",fjMSD[32],"fjMSD_JESRelativePtEC2Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativeStatECUp",fjMSD[33],"fjMSD_JESRelativeStatECUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativeStatECDown",fjMSD[34],"fjMSD_JESRelativeStatECDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativeStatFSRUp",fjMSD[35],"fjMSD_JESRelativeStatFSRUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESRelativeStatFSRDown",fjMSD[36],"fjMSD_JESRelativeStatFSRDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESSinglePionECALUp",fjMSD[37],"fjMSD_JESSinglePionECALUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESSinglePionECALDown",fjMSD[38],"fjMSD_JESSinglePionECALDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESSinglePionHCALUp",fjMSD[39],"fjMSD_JESSinglePionHCALUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESSinglePionHCALDown",fjMSD[40],"fjMSD_JESSinglePionHCALDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESTimePtEtaUp",fjMSD[41],"fjMSD_JESTimePtEtaUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_JESTimePtEtaDown",fjMSD[42],"fjMSD_JESTimePtEtaDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjRho",fjRho,"fjRho["+TString("nFatJetTrunc")+"]/F");
    Book("fjRawRho",fjRawRho,"fjRawRho["+TString("nFatJetTrunc")+"]/F");
    Book("fjRho2",fjRho2,"fjRho2["+TString("nFatJetTrunc")+"]/F");
    Book("fjRawRho2",fjRawRho2,"fjRawRho2["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr",fjMSD_corr[0],"fjMSD_corr["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESTotalUp",fjMSD_corr[1],"fjMSD_corr_JESTotalUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESTotalDown",fjMSD_corr[2],"fjMSD_corr_JESTotalDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESAbsoluteMPFBiasUp",fjMSD_corr[3],"fjMSD_corr_JESAbsoluteMPFBiasUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESAbsoluteMPFBiasDown",fjMSD_corr[4],"fjMSD_corr_JESAbsoluteMPFBiasDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESAbsoluteScaleUp",fjMSD_corr[5],"fjMSD_corr_JESAbsoluteScaleUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESAbsoluteScaleDown",fjMSD_corr[6],"fjMSD_corr_JESAbsoluteScaleDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESAbsoluteStatUp",fjMSD_corr[7],"fjMSD_corr_JESAbsoluteStatUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESAbsoluteStatDown",fjMSD_corr[8],"fjMSD_corr_JESAbsoluteStatDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESFlavorQCDUp",fjMSD_corr[9],"fjMSD_corr_JESFlavorQCDUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESFlavorQCDDown",fjMSD_corr[10],"fjMSD_corr_JESFlavorQCDDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESFragmentationUp",fjMSD_corr[11],"fjMSD_corr_JESFragmentationUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESFragmentationDown",fjMSD_corr[12],"fjMSD_corr_JESFragmentationDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESPileUpDataMCUp",fjMSD_corr[13],"fjMSD_corr_JESPileUpDataMCUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESPileUpDataMCDown",fjMSD_corr[14],"fjMSD_corr_JESPileUpDataMCDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESPileUpPtBBUp",fjMSD_corr[15],"fjMSD_corr_JESPileUpPtBBUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESPileUpPtBBDown",fjMSD_corr[16],"fjMSD_corr_JESPileUpPtBBDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESPileUpPtEC1Up",fjMSD_corr[17],"fjMSD_corr_JESPileUpPtEC1Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESPileUpPtEC1Down",fjMSD_corr[18],"fjMSD_corr_JESPileUpPtEC1Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESPileUpPtEC2Up",fjMSD_corr[19],"fjMSD_corr_JESPileUpPtEC2Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESPileUpPtEC2Down",fjMSD_corr[20],"fjMSD_corr_JESPileUpPtEC2Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESPileUpPtRefUp",fjMSD_corr[21],"fjMSD_corr_JESPileUpPtRefUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESPileUpPtRefDown",fjMSD_corr[22],"fjMSD_corr_JESPileUpPtRefDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativeFSRUp",fjMSD_corr[23],"fjMSD_corr_JESRelativeFSRUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativeFSRDown",fjMSD_corr[24],"fjMSD_corr_JESRelativeFSRDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativeJEREC1Up",fjMSD_corr[25],"fjMSD_corr_JESRelativeJEREC1Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativeJEREC1Down",fjMSD_corr[26],"fjMSD_corr_JESRelativeJEREC1Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativePtBBUp",fjMSD_corr[27],"fjMSD_corr_JESRelativePtBBUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativePtBBDown",fjMSD_corr[28],"fjMSD_corr_JESRelativePtBBDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativePtEC1Up",fjMSD_corr[29],"fjMSD_corr_JESRelativePtEC1Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativePtEC1Down",fjMSD_corr[30],"fjMSD_corr_JESRelativePtEC1Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativePtEC2Up",fjMSD_corr[31],"fjMSD_corr_JESRelativePtEC2Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativePtEC2Down",fjMSD_corr[32],"fjMSD_corr_JESRelativePtEC2Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativeStatECUp",fjMSD_corr[33],"fjMSD_corr_JESRelativeStatECUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativeStatECDown",fjMSD_corr[34],"fjMSD_corr_JESRelativeStatECDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativeStatFSRUp",fjMSD_corr[35],"fjMSD_corr_JESRelativeStatFSRUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESRelativeStatFSRDown",fjMSD_corr[36],"fjMSD_corr_JESRelativeStatFSRDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESSinglePionECALUp",fjMSD_corr[37],"fjMSD_corr_JESSinglePionECALUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESSinglePionECALDown",fjMSD_corr[38],"fjMSD_corr_JESSinglePionECALDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESSinglePionHCALUp",fjMSD_corr[39],"fjMSD_corr_JESSinglePionHCALUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESSinglePionHCALDown",fjMSD_corr[40],"fjMSD_corr_JESSinglePionHCALDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESTimePtEtaUp",fjMSD_corr[41],"fjMSD_corr_JESTimePtEtaUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjMSD_corr_JESTimePtEtaDown",fjMSD_corr[42],"fjMSD_corr_JESTimePtEtaDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt",fjPt[0],"fjPt["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESTotalUp",fjPt[1],"fjPt_JESTotalUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESTotalDown",fjPt[2],"fjPt_JESTotalDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESAbsoluteMPFBiasUp",fjPt[3],"fjPt_JESAbsoluteMPFBiasUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESAbsoluteMPFBiasDown",fjPt[4],"fjPt_JESAbsoluteMPFBiasDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESAbsoluteScaleUp",fjPt[5],"fjPt_JESAbsoluteScaleUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESAbsoluteScaleDown",fjPt[6],"fjPt_JESAbsoluteScaleDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESAbsoluteStatUp",fjPt[7],"fjPt_JESAbsoluteStatUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESAbsoluteStatDown",fjPt[8],"fjPt_JESAbsoluteStatDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESFlavorQCDUp",fjPt[9],"fjPt_JESFlavorQCDUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESFlavorQCDDown",fjPt[10],"fjPt_JESFlavorQCDDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESFragmentationUp",fjPt[11],"fjPt_JESFragmentationUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESFragmentationDown",fjPt[12],"fjPt_JESFragmentationDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESPileUpDataMCUp",fjPt[13],"fjPt_JESPileUpDataMCUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESPileUpDataMCDown",fjPt[14],"fjPt_JESPileUpDataMCDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESPileUpPtBBUp",fjPt[15],"fjPt_JESPileUpPtBBUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESPileUpPtBBDown",fjPt[16],"fjPt_JESPileUpPtBBDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESPileUpPtEC1Up",fjPt[17],"fjPt_JESPileUpPtEC1Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESPileUpPtEC1Down",fjPt[18],"fjPt_JESPileUpPtEC1Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESPileUpPtEC2Up",fjPt[19],"fjPt_JESPileUpPtEC2Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESPileUpPtEC2Down",fjPt[20],"fjPt_JESPileUpPtEC2Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESPileUpPtRefUp",fjPt[21],"fjPt_JESPileUpPtRefUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESPileUpPtRefDown",fjPt[22],"fjPt_JESPileUpPtRefDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativeFSRUp",fjPt[23],"fjPt_JESRelativeFSRUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativeFSRDown",fjPt[24],"fjPt_JESRelativeFSRDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativeJEREC1Up",fjPt[25],"fjPt_JESRelativeJEREC1Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativeJEREC1Down",fjPt[26],"fjPt_JESRelativeJEREC1Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativePtBBUp",fjPt[27],"fjPt_JESRelativePtBBUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativePtBBDown",fjPt[28],"fjPt_JESRelativePtBBDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativePtEC1Up",fjPt[29],"fjPt_JESRelativePtEC1Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativePtEC1Down",fjPt[30],"fjPt_JESRelativePtEC1Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativePtEC2Up",fjPt[31],"fjPt_JESRelativePtEC2Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativePtEC2Down",fjPt[32],"fjPt_JESRelativePtEC2Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativeStatECUp",fjPt[33],"fjPt_JESRelativeStatECUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativeStatECDown",fjPt[34],"fjPt_JESRelativeStatECDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativeStatFSRUp",fjPt[35],"fjPt_JESRelativeStatFSRUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESRelativeStatFSRDown",fjPt[36],"fjPt_JESRelativeStatFSRDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESSinglePionECALUp",fjPt[37],"fjPt_JESSinglePionECALUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESSinglePionECALDown",fjPt[38],"fjPt_JESSinglePionECALDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESSinglePionHCALUp",fjPt[39],"fjPt_JESSinglePionHCALUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESSinglePionHCALDown",fjPt[40],"fjPt_JESSinglePionHCALDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESTimePtEtaUp",fjPt[41],"fjPt_JESTimePtEtaUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjPt_JESTimePtEtaDown",fjPt[42],"fjPt_JESTimePtEtaDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjPhi",fjPhi,"fjPhi["+TString("nFatJetTrunc")+"]/F");
    Book("fjEta",fjEta,"fjEta["+TString("nFatJetTrunc")+"]/F");
    Book("fjNconst",fjNconst,"fjNconst["+TString("nFatJetTrunc")+"]/F");
    Book("fjM",fjM[0],"fjM["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESTotalUp",fjM[1],"fjM_JESTotalUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESTotalDown",fjM[2],"fjM_JESTotalDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESAbsoluteMPFBiasUp",fjM[3],"fjM_JESAbsoluteMPFBiasUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESAbsoluteMPFBiasDown",fjM[4],"fjM_JESAbsoluteMPFBiasDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESAbsoluteScaleUp",fjM[5],"fjM_JESAbsoluteScaleUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESAbsoluteScaleDown",fjM[6],"fjM_JESAbsoluteScaleDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESAbsoluteStatUp",fjM[7],"fjM_JESAbsoluteStatUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESAbsoluteStatDown",fjM[8],"fjM_JESAbsoluteStatDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESFlavorQCDUp",fjM[9],"fjM_JESFlavorQCDUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESFlavorQCDDown",fjM[10],"fjM_JESFlavorQCDDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESFragmentationUp",fjM[11],"fjM_JESFragmentationUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESFragmentationDown",fjM[12],"fjM_JESFragmentationDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESPileUpDataMCUp",fjM[13],"fjM_JESPileUpDataMCUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESPileUpDataMCDown",fjM[14],"fjM_JESPileUpDataMCDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESPileUpPtBBUp",fjM[15],"fjM_JESPileUpPtBBUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESPileUpPtBBDown",fjM[16],"fjM_JESPileUpPtBBDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESPileUpPtEC1Up",fjM[17],"fjM_JESPileUpPtEC1Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESPileUpPtEC1Down",fjM[18],"fjM_JESPileUpPtEC1Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESPileUpPtEC2Up",fjM[19],"fjM_JESPileUpPtEC2Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESPileUpPtEC2Down",fjM[20],"fjM_JESPileUpPtEC2Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESPileUpPtRefUp",fjM[21],"fjM_JESPileUpPtRefUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESPileUpPtRefDown",fjM[22],"fjM_JESPileUpPtRefDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativeFSRUp",fjM[23],"fjM_JESRelativeFSRUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativeFSRDown",fjM[24],"fjM_JESRelativeFSRDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativeJEREC1Up",fjM[25],"fjM_JESRelativeJEREC1Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativeJEREC1Down",fjM[26],"fjM_JESRelativeJEREC1Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativePtBBUp",fjM[27],"fjM_JESRelativePtBBUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativePtBBDown",fjM[28],"fjM_JESRelativePtBBDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativePtEC1Up",fjM[29],"fjM_JESRelativePtEC1Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativePtEC1Down",fjM[30],"fjM_JESRelativePtEC1Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativePtEC2Up",fjM[31],"fjM_JESRelativePtEC2Up["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativePtEC2Down",fjM[32],"fjM_JESRelativePtEC2Down["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativeStatECUp",fjM[33],"fjM_JESRelativeStatECUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativeStatECDown",fjM[34],"fjM_JESRelativeStatECDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativeStatFSRUp",fjM[35],"fjM_JESRelativeStatFSRUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESRelativeStatFSRDown",fjM[36],"fjM_JESRelativeStatFSRDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESSinglePionECALUp",fjM[37],"fjM_JESSinglePionECALUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESSinglePionECALDown",fjM[38],"fjM_JESSinglePionECALDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESSinglePionHCALUp",fjM[39],"fjM_JESSinglePionHCALUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESSinglePionHCALDown",fjM[40],"fjM_JESSinglePionHCALDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESTimePtEtaUp",fjM[41],"fjM_JESTimePtEtaUp["+TString("nFatJetTrunc")+"]/F");
    Book("fjM_JESTimePtEtaDown",fjM[42],"fjM_JESTimePtEtaDown["+TString("nFatJetTrunc")+"]/F");
    Book("fjMaxCSV",fjMaxCSV,"fjMaxCSV["+TString("nFatJetTrunc")+"]/F");
    Book("fjSubMaxCSV",fjSubMaxCSV,"fjSubMaxCSV["+TString("nFatJetTrunc")+"]/F");
    Book("fjMinCSV",fjMinCSV,"fjMinCSV["+TString("nFatJetTrunc")+"]/F");
    Book("fjDoubleCSV",fjDoubleCSV,"fjDoubleCSV["+TString("nFatJetTrunc")+"]/F");
    Book("fjDeepB",fjDeepB,"fjDeepB["+TString("nFatJetTrunc")+"]/F");
    Book("fjDeepProbH",fjDeepProbH,"fjDeepProbH["+TString("nFatJetTrunc")+"]/F");
    Book("fjgbb",fjgbb,"fjgbb["+TString("nFatJetTrunc")+"]/I");
    Book("fjNbs",fjNbs,"fjNbs["+TString("nFatJetTrunc")+"]/I");
    Book("fjGenPt",fjGenPt,"fjGenPt["+TString("nFatJetTrunc")+"]/F");
    Book("fjGenSize",fjGenSize,"fjGenSize["+TString("nFatJetTrunc")+"]/F");
    Book("fjIsMatched",fjIsMatched,"fjIsMatched["+TString("nFatJetTrunc")+"]/I");
    Book("fjGenWPt",fjGenWPt,"fjGenWPt["+TString("nFatJetTrunc")+"]/F");
    Book("fjGenWSize",fjGenWSize,"fjGenWSize["+TString("nFatJetTrunc")+"]/F");
    Book("fjIsWMatched",fjIsWMatched,"fjIsWMatched["+TString("nFatJetTrunc")+"]/I");
    Book("fjHighestPtGen",fjHighestPtGen,"fjHighestPtGen["+TString("nFatJetTrunc")+"]/I");
    Book("fjHighestPtGenPt",fjHighestPtGenPt,"fjHighestPtGenPt["+TString("nFatJetTrunc")+"]/F");
    Book("fjIsTight",fjIsTight,"fjIsTight["+TString("nFatJetTrunc")+"]/I");
    Book("fjIsLoose",fjIsLoose,"fjIsLoose["+TString("nFatJetTrunc")+"]/I");
    Book("fjRawPt",fjRawPt,"fjRawPt["+TString("nFatJetTrunc")+"]/F");
    Book("fjNHF",fjNHF,"fjNHF["+TString("nFatJetTrunc")+"]/I");
    Book("fjHTTMass",fjHTTMass,"fjHTTMass["+TString("nFatJetTrunc")+"]/F");
    Book("fjHTTFRec",fjHTTFRec,"fjHTTFRec["+TString("nFatJetTrunc")+"]/F");
    Book("fjIsClean",fjIsClean,"fjIsClean["+TString("nFatJetTrunc")+"]/I");
    Book("fjNPartons",fjNPartons,"fjNPartons["+TString("nFatJetTrunc")+"]/I");
    Book("fjNBPartons",fjNBPartons,"fjNBPartons["+TString("nFatJetTrunc")+"]/I");
    Book("fjNCPartons",fjNCPartons,"fjNCPartons["+TString("nFatJetTrunc")+"]/I");
    Book("fjPartonM",fjPartonM,"fjPartonM["+TString("nFatJetTrunc")+"]/F");
    Book("fjPartonPt",fjPartonPt,"fjPartonPt["+TString("nFatJetTrunc")+"]/F");
    Book("fjPartonEta",fjPartonEta,"fjPartonEta["+TString("nFatJetTrunc")+"]/F");
    Book("fjGenNumB",fjGenNumB,"fjGenNumB["+TString("nFatJetTrunc")+"]/I");
  }
  if (is_darkg) {
    Book("genPho1Pt",&genPho1Pt,"genPho1Pt/F");
    Book("genPho1Eta",&genPho1Eta,"genPho1Eta/F");
    Book("genPho1Phi",&genPho1Phi,"genPho1Phi/F");
    Book("vtxNTrk",&vtxNTrk,"vtxNTrk/I");
    Book("vtxScore",&vtxScore,"vtxScore/F");
    Book("vtxChi2",&vtxChi2,"vtxChi2/F");
  }
  if (is_fatjet) {
    if (is_vh) {
      Book("fjQ",fjQ,"fjQ["+TString("nFatJetTrunc")+"]/F");
    }
  }
}