// THIS FILE IS AUTOGENERATED //
#include "../interface/GeneralTree.h"
// STARTCUSTOM INCLUDE

#include <iostream>

TString GeneralTree::csvShiftName(GeneralTree::csvShift shift) 
{
  switch (shift) {
    case csvCent        : return "central"      ;
    case csvJESup       : return "up_jes"       ;
    case csvJESdown     : return "down_jes"     ;
    case csvLFup        : return "up_lf"        ;
    case csvLFdown      : return "down_lf"      ;
    case csvHFup        : return "up_hf"        ;
    case csvHFdown      : return "down_hf"      ;
    case csvHFStats1up  : return "up_hfstats1"  ;
    case csvHFStats1down: return "down_hfstats1";
    case csvHFStats2up  : return "up_hfstats2"  ;
    case csvHFStats2down: return "down_hfstats2";
    case csvLFStats1up  : return "up_lfstats1"  ;
    case csvLFStats1down: return "down_lfstats1";
    case csvLFStats2up  : return "up_lfstats2"  ;
    case csvLFStats2down: return "down_lfstats2";
    case csvCErr1up     : return "up_cferr1"    ;
    case csvCErr1down   : return "down_cferr1"  ;
    case csvCErr2up     : return "up_cferr2"    ;
    case csvCErr2down   : return "down_cferr2"  ;
    default : return "central";
  }
}
//ENDCUSTOM
TString jesName(shiftjes e) {
  switch(e) {
    case shiftjes::kNominal : return "Nominal";
    case shiftjes::kJESTotalUp : return "JESTotalUp";
    case shiftjes::kJESTotalDown : return "JESTotalDown";
    case shiftjes::kJESAbsoluteMPFBiasUp : return "JESAbsoluteMPFBiasUp";
    case shiftjes::kJESAbsoluteMPFBiasDown : return "JESAbsoluteMPFBiasDown";
    case shiftjes::kJESAbsoluteScaleUp : return "JESAbsoluteScaleUp";
    case shiftjes::kJESAbsoluteScaleDown : return "JESAbsoluteScaleDown";
    case shiftjes::kJESAbsoluteStatUp : return "JESAbsoluteStatUp";
    case shiftjes::kJESAbsoluteStatDown : return "JESAbsoluteStatDown";
    case shiftjes::kJESFlavorQCDUp : return "JESFlavorQCDUp";
    case shiftjes::kJESFlavorQCDDown : return "JESFlavorQCDDown";
    case shiftjes::kJESFragmentationUp : return "JESFragmentationUp";
    case shiftjes::kJESFragmentationDown : return "JESFragmentationDown";
    case shiftjes::kJESPileUpDataMCUp : return "JESPileUpDataMCUp";
    case shiftjes::kJESPileUpDataMCDown : return "JESPileUpDataMCDown";
    case shiftjes::kJESPileUpPtBBUp : return "JESPileUpPtBBUp";
    case shiftjes::kJESPileUpPtBBDown : return "JESPileUpPtBBDown";
    case shiftjes::kJESPileUpPtEC1Up : return "JESPileUpPtEC1Up";
    case shiftjes::kJESPileUpPtEC1Down : return "JESPileUpPtEC1Down";
    case shiftjes::kJESPileUpPtEC2Up : return "JESPileUpPtEC2Up";
    case shiftjes::kJESPileUpPtEC2Down : return "JESPileUpPtEC2Down";
    case shiftjes::kJESPileUpPtRefUp : return "JESPileUpPtRefUp";
    case shiftjes::kJESPileUpPtRefDown : return "JESPileUpPtRefDown";
    case shiftjes::kJESRelativeFSRUp : return "JESRelativeFSRUp";
    case shiftjes::kJESRelativeFSRDown : return "JESRelativeFSRDown";
    case shiftjes::kJESRelativeJEREC1Up : return "JESRelativeJEREC1Up";
    case shiftjes::kJESRelativeJEREC1Down : return "JESRelativeJEREC1Down";
    case shiftjes::kJESRelativePtBBUp : return "JESRelativePtBBUp";
    case shiftjes::kJESRelativePtBBDown : return "JESRelativePtBBDown";
    case shiftjes::kJESRelativePtEC1Up : return "JESRelativePtEC1Up";
    case shiftjes::kJESRelativePtEC1Down : return "JESRelativePtEC1Down";
    case shiftjes::kJESRelativePtEC2Up : return "JESRelativePtEC2Up";
    case shiftjes::kJESRelativePtEC2Down : return "JESRelativePtEC2Down";
    case shiftjes::kJESRelativeStatECUp : return "JESRelativeStatECUp";
    case shiftjes::kJESRelativeStatECDown : return "JESRelativeStatECDown";
    case shiftjes::kJESRelativeStatFSRUp : return "JESRelativeStatFSRUp";
    case shiftjes::kJESRelativeStatFSRDown : return "JESRelativeStatFSRDown";
    case shiftjes::kJESSinglePionECALUp : return "JESSinglePionECALUp";
    case shiftjes::kJESSinglePionECALDown : return "JESSinglePionECALDown";
    case shiftjes::kJESSinglePionHCALUp : return "JESSinglePionHCALUp";
    case shiftjes::kJESSinglePionHCALDown : return "JESSinglePionHCALDown";
    case shiftjes::kJESTimePtEtaUp : return "JESTimePtEtaUp";
    case shiftjes::kJESTimePtEtaDown : return "JESTimePtEtaDown";
    default : return "N";
  }
}
GeneralTree::GeneralTree() {
// STARTCUSTOM CONSTRUCTOR
    for (auto ibeta : ibetas) {
        for (auto N : Ns) {
            for (auto order : orders) {
                ECFParams p;
                p.ibeta = ibeta;
                p.N = N;
                p.order = order;
                ecfParams.push_back(p);
                fjECFNs[p] = new float[2];
            }
        }
    }

    for (unsigned iShift=0; iShift!=bNShift; ++iShift) {
        for (unsigned iJet=0; iJet!=bNJet; ++iJet) {
            for (unsigned iTags=0; iTags!=bNTags; ++iTags) {
                BTagParams p;
                p.jet = (BTagJet)iJet;
                p.tag = (BTagTags)iTags;
                p.shift = (BTagShift)iShift;
                btagParams.push_back(p);
                sf_btags[p] = 1;
            }
        }
    }

    for (unsigned iShift=0; iShift<nCsvShifts; iShift++) {
        csvShift shift = csvShifts[iShift];
        sf_csvWeights[shift] = 1;
    }
// ENDCUSTOM
  Reset();
}
GeneralTree::~GeneralTree() {
// STARTCUSTOM DESTRUCTOR
    for (auto p : ecfParams) {
        delete[] fjECFNs[p];
    }
// ENDCUSTOM
}
void GeneralTree::SetAuxTree(TTree *t) {
// STARTCUSTOM AUX
    for (auto p : ecfParams) {
        TString ecfn(makeECFString(p));
        t->Branch("fj"+ecfn,&(fjECFNs[p][0]),"fj"+ecfn+"/F");
    }
// ENDCUSTOM
}
void GeneralTree::Reset() {
// STARTCUSTOM RESET
    for (auto p : ecfParams) {
      for (int i = 0; i != 2; ++i)
        fjECFNs[p][i] = -1;
    }

    for (auto p : btagParams) {
        sf_btags[p] = 1;
    }
    for (unsigned iShift=0; iShift<nCsvShifts; iShift++) {
        csvShift shift = csvShifts[iShift];
        sf_csvWeights[shift] = 1;
    }
    for (auto iter=signal_weights.begin(); iter!=signal_weights.end(); ++iter) {
        signal_weights[iter->first] = 1;
    }
// ENDCUSTOM
  runNumber = 0;
  lumiNumber = 0;
  eventNumber = -99;
  isData = 0;
  npv = 0;
  pu = 0;
  rho = -99;
  mcWeight = -99;
  trigger = 0;
  metFilter = 0;
  filter_maxRecoil = -99;
  filter_whichRecoil = 0;
  badECALFilter = 1;
  category = 0;
  npdf = 0;
  nscale = 0;
  sf_ewkV = 1;
  sf_qcdV = 1;
  sf_lepID = 1;
  sf_lepIso = 1;
  sf_lepTrack = 1;
  sf_pho = 1;
  sf_eleTrig = 1;
  sf_muTrig = 1;
  sf_phoTrig = 1;
  sf_l1Prefire = 1;
  sf_pu = 1;
  sf_npv = 1;
  sf_phoPurity = 1;
  calomet = -99;
  calometphi = -99;
  genmet = -99;
  genmetphi = -99;
  genMjj = -99;
  whichRecoil = 0;
  genJet1Pt = -99;
  genJet2Pt = -99;
  genJet1Eta = -99;
  genJet2Eta = -99;
  genJet1Phi = -99;
  genJet2Phi = -99;
  nJetMax = 0;
  nLoosePhoton = 0;
  nTightPhoton = 0;
  loosePho1IsTight = 0;
  loosePho1Pt = -99;
  loosePho1Eta = -99;
  loosePho1Phi = -99;
  loosePho1r9 = -99;
  loosePho1chIso = -99;
  loosePho1nhIso = -99;
  loosePho1phIso = -99;
  loosePho1hOverE = -99;
  loosePho1sieie = -99;
  loosePho1SelBit = 0;
  nLooseElectron = 0;
  nLooseMuon = 0;
  nTightElectron = 0;
  nTightMuon = 0;
  diLepMass = -99;
  nTau = 0;
  genPho1Pt = -99;
  genPho1Eta = -99;
  genPho1Phi = -99;
  vtxNTrk = 0;
  vtxScore = -99;
  vtxChi2 = -99;
  pdfUp = 1;
  pdfDown = 1;
  lheHT = -99;
  lheNjets = 0;
  for (int iA=0; iA!=4; ++iA) {
    muonPt[iA] = -99;
    muonEta[iA] = -99;
    muonPhi[iA] = -99;
    muonSelBit[iA] = 0;
    muonPdgId[iA] = 0;
    muonD0[iA] = -99;
    muonDZ[iA] = -99;
    muonIsSoftMuon[iA] = 0;
    muonCombIso[iA] = -99;
    muonSfLoose[iA] = -99;
    muonSfMedium[iA] = -99;
    muonSfTight[iA] = -99;
    muonSfUnc[iA] = -99;
    muonSfReco[iA] = -99;
    muTrigMatch[iA] = 0;
    electronPt[iA] = -99;
    electronEta[iA] = -99;
    electronPhi[iA] = -99;
    electronSelBit[iA] = 0;
    electronPdgId[iA] = 0;
    electronPhoMatch[iA] = 0;
    electronLPhoMatch[iA] = 0;
    electronSfLoose[iA] = -99;
    electronSfMedium[iA] = -99;
    electronSfTight[iA] = -99;
    electronSfUnc[iA] = -99;
    electronSfReco[iA] = -99;
    electronSfMvaWP90[iA] = -99;
    electronSfMvaWP80[iA] = -99;
    electronD0[iA] = -99;
    electronDZ[iA] = -99;
    electronNMissingHits[iA] = 0;
    electronTripleCharge[iA] = 0;
    electronCombIso[iA] = -99;
    eleTrigMatch[iA] = 0;
    tauPt[iA] = -99;
    tauEta[iA] = -99;
    tauPhi[iA] = -99;
  }
  for (int iA=0; iA!=20; ++iA) {
    jetEta[iA] = -99;
    jetPhi[iA] = -99;
    jetGenPt[iA] = -99;
    jetDeepCSV[iA] = -99;
    jetDeepQG[iA] = -99;
    jetFlav[iA] = 0;
    jetIsTight[iA] = 0;
    jetIsPU[iA] = 0;
  }
  for (int iA=0; iA!=6; ++iA) {
    scale[iA] = 1;
  }
  for (int iS=0; iS!=43; ++iS) {
    nJet[iS] = 0;
  }
  for (int iS=0; iS!=3; ++iS) {
    pfmet[iS] = -99;
    pfmetphi[iS] = -99;
    pfmetnomu[iS] = -99;
    puppimet[iS] = -99;
    puppimetphi[iS] = -99;
    puppiUZmag[iS] = -99;
    puppiUAmag[iS] = -99;
    puppiUZphi[iS] = -99;
    puppiUAphi[iS] = -99;
    pfUZmag[iS] = -99;
    pfUAmag[iS] = -99;
    pfUZphi[iS] = -99;
    pfUAphi[iS] = -99;
    jet12Mass[iS] = -99;
    jet12DEta[iS] = -99;
    jet12DPhi[iS] = -99;
    dphipfmet[iS] = 999;
    dphipuppimet[iS] = 999;
    dphipuppiUZ[iS] = 999;
    dphipuppiUA[iS] = 999;
    dphipfUZ[iS] = 999;
    dphipfUA[iS] = 999;
  }
  for (int iS=0; iS!=43; ++iS) {
    for (int iA=0; iA!=20; ++iA) {
      jetPt[iS][iA] = -99;
      jetE[iS][iA] = -99;
    }
  }
}
void GeneralTree::WriteTree(TTree *t) {
  treePtr = t;
// STARTCUSTOM WRITE
    for (auto iter=signal_weights.begin(); iter!=signal_weights.end(); ++iter) {
        Book("rw_"+iter->first,&(signal_weights[iter->first]),"rw_"+iter->first+"/F");
    }
    for (auto p : ecfParams) {
        TString ecfn(makeECFString(p));
        Book("fj"+ecfn,fjECFNs[p],"fj"+ecfn+"["+fjTreeSize()+"]/F");
    }

    for (auto p : btagParams) {
        TString btagn(makeBTagSFString(p));
        Book(btagn,&(sf_btags[p]),btagn+"/F");
    }

    if (btagWeights) {
        for (unsigned iShift=0; iShift<nCsvShifts; iShift++) {
            csvShift shift = csvShifts[iShift];
            TString csvWeightString = makeCsvWeightString(shift, useCMVA);
            Book(csvWeightString, &(sf_csvWeights[shift]), csvWeightString+"/F");
        }
    }
// ENDCUSTOM
  Book("runNumber",&runNumber,"runNumber/I");
  Book("lumiNumber",&lumiNumber,"lumiNumber/I");
  Book("eventNumber",&eventNumber,"eventNumber/l");
  Book("isData",&isData,"isData/I");
  Book("npv",&npv,"npv/I");
  Book("pu",&pu,"pu/I");
  Book("rho",&rho,"rho/F");
  Book("mcWeight",&mcWeight,"mcWeight/F");
  Book("trigger",&trigger,"trigger/I");
  Book("metFilter",&metFilter,"metFilter/I");
  Book("filter_maxRecoil",&filter_maxRecoil,"filter_maxRecoil/F");
  Book("filter_whichRecoil",&filter_whichRecoil,"filter_whichRecoil/I");
  Book("badECALFilter",&badECALFilter,"badECALFilter/I");
  Book("category",&category,"category/I");
  Book("npdf",&npdf,"npdf/I");
  Book("nscale",&nscale,"nscale/I");
  Book("sf_ewkV",&sf_ewkV,"sf_ewkV/F");
  Book("sf_qcdV",&sf_qcdV,"sf_qcdV/F");
  Book("sf_lepID",&sf_lepID,"sf_lepID/F");
  Book("sf_lepIso",&sf_lepIso,"sf_lepIso/F");
  Book("sf_lepTrack",&sf_lepTrack,"sf_lepTrack/F");
  Book("sf_pho",&sf_pho,"sf_pho/F");
  Book("sf_eleTrig",&sf_eleTrig,"sf_eleTrig/F");
  Book("sf_muTrig",&sf_muTrig,"sf_muTrig/F");
  Book("sf_phoTrig",&sf_phoTrig,"sf_phoTrig/F");
  Book("sf_l1Prefire",&sf_l1Prefire,"sf_l1Prefire/F");
  Book("sf_pu",&sf_pu,"sf_pu/F");
  Book("sf_npv",&sf_npv,"sf_npv/F");
  Book("sf_phoPurity",&sf_phoPurity,"sf_phoPurity/F");
  Book("pfmet",&(pfmet[0]),"pfmet/F");
  Book("pfmet_JESTotalUp",&(pfmet[1]),"pfmet_JESTotalUp/F");
  Book("pfmet_JESTotalDown",&(pfmet[2]),"pfmet_JESTotalDown/F");
  Book("pfmetphi",&(pfmetphi[0]),"pfmetphi/F");
  Book("pfmetphi_JESTotalUp",&(pfmetphi[1]),"pfmetphi_JESTotalUp/F");
  Book("pfmetphi_JESTotalDown",&(pfmetphi[2]),"pfmetphi_JESTotalDown/F");
  Book("pfmetnomu",&(pfmetnomu[0]),"pfmetnomu/F");
  Book("pfmetnomu_JESTotalUp",&(pfmetnomu[1]),"pfmetnomu_JESTotalUp/F");
  Book("pfmetnomu_JESTotalDown",&(pfmetnomu[2]),"pfmetnomu_JESTotalDown/F");
  Book("puppimet",&(puppimet[0]),"puppimet/F");
  Book("puppimet_JESTotalUp",&(puppimet[1]),"puppimet_JESTotalUp/F");
  Book("puppimet_JESTotalDown",&(puppimet[2]),"puppimet_JESTotalDown/F");
  Book("puppimetphi",&(puppimetphi[0]),"puppimetphi/F");
  Book("puppimetphi_JESTotalUp",&(puppimetphi[1]),"puppimetphi_JESTotalUp/F");
  Book("puppimetphi_JESTotalDown",&(puppimetphi[2]),"puppimetphi_JESTotalDown/F");
  Book("calomet",&calomet,"calomet/F");
  Book("calometphi",&calometphi,"calometphi/F");
  Book("genmet",&genmet,"genmet/F");
  Book("genmetphi",&genmetphi,"genmetphi/F");
  Book("whichRecoil",&whichRecoil,"whichRecoil/I");
  Book("puppiUZmag",&(puppiUZmag[0]),"puppiUZmag/F");
  Book("puppiUZmag_JESTotalUp",&(puppiUZmag[1]),"puppiUZmag_JESTotalUp/F");
  Book("puppiUZmag_JESTotalDown",&(puppiUZmag[2]),"puppiUZmag_JESTotalDown/F");
  Book("puppiUAmag",&(puppiUAmag[0]),"puppiUAmag/F");
  Book("puppiUAmag_JESTotalUp",&(puppiUAmag[1]),"puppiUAmag_JESTotalUp/F");
  Book("puppiUAmag_JESTotalDown",&(puppiUAmag[2]),"puppiUAmag_JESTotalDown/F");
  Book("puppiUZphi",&(puppiUZphi[0]),"puppiUZphi/F");
  Book("puppiUZphi_JESTotalUp",&(puppiUZphi[1]),"puppiUZphi_JESTotalUp/F");
  Book("puppiUZphi_JESTotalDown",&(puppiUZphi[2]),"puppiUZphi_JESTotalDown/F");
  Book("puppiUAphi",&(puppiUAphi[0]),"puppiUAphi/F");
  Book("puppiUAphi_JESTotalUp",&(puppiUAphi[1]),"puppiUAphi_JESTotalUp/F");
  Book("puppiUAphi_JESTotalDown",&(puppiUAphi[2]),"puppiUAphi_JESTotalDown/F");
  Book("pfUZmag",&(pfUZmag[0]),"pfUZmag/F");
  Book("pfUZmag_JESTotalUp",&(pfUZmag[1]),"pfUZmag_JESTotalUp/F");
  Book("pfUZmag_JESTotalDown",&(pfUZmag[2]),"pfUZmag_JESTotalDown/F");
  Book("pfUAmag",&(pfUAmag[0]),"pfUAmag/F");
  Book("pfUAmag_JESTotalUp",&(pfUAmag[1]),"pfUAmag_JESTotalUp/F");
  Book("pfUAmag_JESTotalDown",&(pfUAmag[2]),"pfUAmag_JESTotalDown/F");
  Book("pfUZphi",&(pfUZphi[0]),"pfUZphi/F");
  Book("pfUZphi_JESTotalUp",&(pfUZphi[1]),"pfUZphi_JESTotalUp/F");
  Book("pfUZphi_JESTotalDown",&(pfUZphi[2]),"pfUZphi_JESTotalDown/F");
  Book("pfUAphi",&(pfUAphi[0]),"pfUAphi/F");
  Book("pfUAphi_JESTotalUp",&(pfUAphi[1]),"pfUAphi_JESTotalUp/F");
  Book("pfUAphi_JESTotalDown",&(pfUAphi[2]),"pfUAphi_JESTotalDown/F");
  Book("jet12Mass",&(jet12Mass[0]),"jet12Mass/F");
  Book("jet12Mass_JESTotalUp",&(jet12Mass[1]),"jet12Mass_JESTotalUp/F");
  Book("jet12Mass_JESTotalDown",&(jet12Mass[2]),"jet12Mass_JESTotalDown/F");
  Book("jet12DEta",&(jet12DEta[0]),"jet12DEta/F");
  Book("jet12DEta_JESTotalUp",&(jet12DEta[1]),"jet12DEta_JESTotalUp/F");
  Book("jet12DEta_JESTotalDown",&(jet12DEta[2]),"jet12DEta_JESTotalDown/F");
  Book("jet12DPhi",&(jet12DPhi[0]),"jet12DPhi/F");
  Book("jet12DPhi_JESTotalUp",&(jet12DPhi[1]),"jet12DPhi_JESTotalUp/F");
  Book("jet12DPhi_JESTotalDown",&(jet12DPhi[2]),"jet12DPhi_JESTotalDown/F");
  Book("dphipfmet",&(dphipfmet[0]),"dphipfmet/F");
  Book("dphipfmet_JESTotalUp",&(dphipfmet[1]),"dphipfmet_JESTotalUp/F");
  Book("dphipfmet_JESTotalDown",&(dphipfmet[2]),"dphipfmet_JESTotalDown/F");
  Book("dphipuppimet",&(dphipuppimet[0]),"dphipuppimet/F");
  Book("dphipuppimet_JESTotalUp",&(dphipuppimet[1]),"dphipuppimet_JESTotalUp/F");
  Book("dphipuppimet_JESTotalDown",&(dphipuppimet[2]),"dphipuppimet_JESTotalDown/F");
  Book("dphipuppiUZ",&(dphipuppiUZ[0]),"dphipuppiUZ/F");
  Book("dphipuppiUZ_JESTotalUp",&(dphipuppiUZ[1]),"dphipuppiUZ_JESTotalUp/F");
  Book("dphipuppiUZ_JESTotalDown",&(dphipuppiUZ[2]),"dphipuppiUZ_JESTotalDown/F");
  Book("dphipuppiUA",&(dphipuppiUA[0]),"dphipuppiUA/F");
  Book("dphipuppiUA_JESTotalUp",&(dphipuppiUA[1]),"dphipuppiUA_JESTotalUp/F");
  Book("dphipuppiUA_JESTotalDown",&(dphipuppiUA[2]),"dphipuppiUA_JESTotalDown/F");
  Book("dphipfUZ",&(dphipfUZ[0]),"dphipfUZ/F");
  Book("dphipfUZ_JESTotalUp",&(dphipfUZ[1]),"dphipfUZ_JESTotalUp/F");
  Book("dphipfUZ_JESTotalDown",&(dphipfUZ[2]),"dphipfUZ_JESTotalDown/F");
  Book("dphipfUA",&(dphipfUA[0]),"dphipfUA/F");
  Book("dphipfUA_JESTotalUp",&(dphipfUA[1]),"dphipfUA_JESTotalUp/F");
  Book("dphipfUA_JESTotalDown",&(dphipfUA[2]),"dphipfUA_JESTotalDown/F");
  Book("genJet1Pt",&genJet1Pt,"genJet1Pt/F");
  Book("genJet2Pt",&genJet2Pt,"genJet2Pt/F");
  Book("genJet1Eta",&genJet1Eta,"genJet1Eta/F");
  Book("genJet2Eta",&genJet2Eta,"genJet2Eta/F");
  Book("genJet1Phi",&genJet1Phi,"genJet1Phi/F");
  Book("genJet2Phi",&genJet2Phi,"genJet2Phi/F");
  Book("nJet",&(nJet[0]),"nJet/I");
  Book("nJet_JESTotalUp",&(nJet[1]),"nJet_JESTotalUp/I");
  Book("nJet_JESTotalDown",&(nJet[2]),"nJet_JESTotalDown/I");
  Book("nJet_JESAbsoluteMPFBiasUp",&(nJet[3]),"nJet_JESAbsoluteMPFBiasUp/I");
  Book("nJet_JESAbsoluteMPFBiasDown",&(nJet[4]),"nJet_JESAbsoluteMPFBiasDown/I");
  Book("nJet_JESAbsoluteScaleUp",&(nJet[5]),"nJet_JESAbsoluteScaleUp/I");
  Book("nJet_JESAbsoluteScaleDown",&(nJet[6]),"nJet_JESAbsoluteScaleDown/I");
  Book("nJet_JESAbsoluteStatUp",&(nJet[7]),"nJet_JESAbsoluteStatUp/I");
  Book("nJet_JESAbsoluteStatDown",&(nJet[8]),"nJet_JESAbsoluteStatDown/I");
  Book("nJet_JESFlavorQCDUp",&(nJet[9]),"nJet_JESFlavorQCDUp/I");
  Book("nJet_JESFlavorQCDDown",&(nJet[10]),"nJet_JESFlavorQCDDown/I");
  Book("nJet_JESFragmentationUp",&(nJet[11]),"nJet_JESFragmentationUp/I");
  Book("nJet_JESFragmentationDown",&(nJet[12]),"nJet_JESFragmentationDown/I");
  Book("nJet_JESPileUpDataMCUp",&(nJet[13]),"nJet_JESPileUpDataMCUp/I");
  Book("nJet_JESPileUpDataMCDown",&(nJet[14]),"nJet_JESPileUpDataMCDown/I");
  Book("nJet_JESPileUpPtBBUp",&(nJet[15]),"nJet_JESPileUpPtBBUp/I");
  Book("nJet_JESPileUpPtBBDown",&(nJet[16]),"nJet_JESPileUpPtBBDown/I");
  Book("nJet_JESPileUpPtEC1Up",&(nJet[17]),"nJet_JESPileUpPtEC1Up/I");
  Book("nJet_JESPileUpPtEC1Down",&(nJet[18]),"nJet_JESPileUpPtEC1Down/I");
  Book("nJet_JESPileUpPtEC2Up",&(nJet[19]),"nJet_JESPileUpPtEC2Up/I");
  Book("nJet_JESPileUpPtEC2Down",&(nJet[20]),"nJet_JESPileUpPtEC2Down/I");
  Book("nJet_JESPileUpPtRefUp",&(nJet[21]),"nJet_JESPileUpPtRefUp/I");
  Book("nJet_JESPileUpPtRefDown",&(nJet[22]),"nJet_JESPileUpPtRefDown/I");
  Book("nJet_JESRelativeFSRUp",&(nJet[23]),"nJet_JESRelativeFSRUp/I");
  Book("nJet_JESRelativeFSRDown",&(nJet[24]),"nJet_JESRelativeFSRDown/I");
  Book("nJet_JESRelativeJEREC1Up",&(nJet[25]),"nJet_JESRelativeJEREC1Up/I");
  Book("nJet_JESRelativeJEREC1Down",&(nJet[26]),"nJet_JESRelativeJEREC1Down/I");
  Book("nJet_JESRelativePtBBUp",&(nJet[27]),"nJet_JESRelativePtBBUp/I");
  Book("nJet_JESRelativePtBBDown",&(nJet[28]),"nJet_JESRelativePtBBDown/I");
  Book("nJet_JESRelativePtEC1Up",&(nJet[29]),"nJet_JESRelativePtEC1Up/I");
  Book("nJet_JESRelativePtEC1Down",&(nJet[30]),"nJet_JESRelativePtEC1Down/I");
  Book("nJet_JESRelativePtEC2Up",&(nJet[31]),"nJet_JESRelativePtEC2Up/I");
  Book("nJet_JESRelativePtEC2Down",&(nJet[32]),"nJet_JESRelativePtEC2Down/I");
  Book("nJet_JESRelativeStatECUp",&(nJet[33]),"nJet_JESRelativeStatECUp/I");
  Book("nJet_JESRelativeStatECDown",&(nJet[34]),"nJet_JESRelativeStatECDown/I");
  Book("nJet_JESRelativeStatFSRUp",&(nJet[35]),"nJet_JESRelativeStatFSRUp/I");
  Book("nJet_JESRelativeStatFSRDown",&(nJet[36]),"nJet_JESRelativeStatFSRDown/I");
  Book("nJet_JESSinglePionECALUp",&(nJet[37]),"nJet_JESSinglePionECALUp/I");
  Book("nJet_JESSinglePionECALDown",&(nJet[38]),"nJet_JESSinglePionECALDown/I");
  Book("nJet_JESSinglePionHCALUp",&(nJet[39]),"nJet_JESSinglePionHCALUp/I");
  Book("nJet_JESSinglePionHCALDown",&(nJet[40]),"nJet_JESSinglePionHCALDown/I");
  Book("nJet_JESTimePtEtaUp",&(nJet[41]),"nJet_JESTimePtEtaUp/I");
  Book("nJet_JESTimePtEtaDown",&(nJet[42]),"nJet_JESTimePtEtaDown/I");
  Book("nJetMax",&nJetMax,"nJetMax/I");
  Book("jetPt",jetPt[0],"jetPt["+TString("nJetMax")+"]/F");
  Book("jetPt_JESTotalUp",jetPt[1],"jetPt_JESTotalUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESTotalDown",jetPt[2],"jetPt_JESTotalDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESAbsoluteMPFBiasUp",jetPt[3],"jetPt_JESAbsoluteMPFBiasUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESAbsoluteMPFBiasDown",jetPt[4],"jetPt_JESAbsoluteMPFBiasDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESAbsoluteScaleUp",jetPt[5],"jetPt_JESAbsoluteScaleUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESAbsoluteScaleDown",jetPt[6],"jetPt_JESAbsoluteScaleDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESAbsoluteStatUp",jetPt[7],"jetPt_JESAbsoluteStatUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESAbsoluteStatDown",jetPt[8],"jetPt_JESAbsoluteStatDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESFlavorQCDUp",jetPt[9],"jetPt_JESFlavorQCDUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESFlavorQCDDown",jetPt[10],"jetPt_JESFlavorQCDDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESFragmentationUp",jetPt[11],"jetPt_JESFragmentationUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESFragmentationDown",jetPt[12],"jetPt_JESFragmentationDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpDataMCUp",jetPt[13],"jetPt_JESPileUpDataMCUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpDataMCDown",jetPt[14],"jetPt_JESPileUpDataMCDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtBBUp",jetPt[15],"jetPt_JESPileUpPtBBUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtBBDown",jetPt[16],"jetPt_JESPileUpPtBBDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtEC1Up",jetPt[17],"jetPt_JESPileUpPtEC1Up["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtEC1Down",jetPt[18],"jetPt_JESPileUpPtEC1Down["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtEC2Up",jetPt[19],"jetPt_JESPileUpPtEC2Up["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtEC2Down",jetPt[20],"jetPt_JESPileUpPtEC2Down["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtRefUp",jetPt[21],"jetPt_JESPileUpPtRefUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESPileUpPtRefDown",jetPt[22],"jetPt_JESPileUpPtRefDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeFSRUp",jetPt[23],"jetPt_JESRelativeFSRUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeFSRDown",jetPt[24],"jetPt_JESRelativeFSRDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeJEREC1Up",jetPt[25],"jetPt_JESRelativeJEREC1Up["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeJEREC1Down",jetPt[26],"jetPt_JESRelativeJEREC1Down["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativePtBBUp",jetPt[27],"jetPt_JESRelativePtBBUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativePtBBDown",jetPt[28],"jetPt_JESRelativePtBBDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativePtEC1Up",jetPt[29],"jetPt_JESRelativePtEC1Up["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativePtEC1Down",jetPt[30],"jetPt_JESRelativePtEC1Down["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativePtEC2Up",jetPt[31],"jetPt_JESRelativePtEC2Up["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativePtEC2Down",jetPt[32],"jetPt_JESRelativePtEC2Down["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeStatECUp",jetPt[33],"jetPt_JESRelativeStatECUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeStatECDown",jetPt[34],"jetPt_JESRelativeStatECDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeStatFSRUp",jetPt[35],"jetPt_JESRelativeStatFSRUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESRelativeStatFSRDown",jetPt[36],"jetPt_JESRelativeStatFSRDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESSinglePionECALUp",jetPt[37],"jetPt_JESSinglePionECALUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESSinglePionECALDown",jetPt[38],"jetPt_JESSinglePionECALDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESSinglePionHCALUp",jetPt[39],"jetPt_JESSinglePionHCALUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESSinglePionHCALDown",jetPt[40],"jetPt_JESSinglePionHCALDown["+TString("nJetMax")+"]/F");
  Book("jetPt_JESTimePtEtaUp",jetPt[41],"jetPt_JESTimePtEtaUp["+TString("nJetMax")+"]/F");
  Book("jetPt_JESTimePtEtaDown",jetPt[42],"jetPt_JESTimePtEtaDown["+TString("nJetMax")+"]/F");
  Book("jetE",jetE[0],"jetE["+TString("nJetMax")+"]/F");
  Book("jetE_JESTotalUp",jetE[1],"jetE_JESTotalUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESTotalDown",jetE[2],"jetE_JESTotalDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESAbsoluteMPFBiasUp",jetE[3],"jetE_JESAbsoluteMPFBiasUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESAbsoluteMPFBiasDown",jetE[4],"jetE_JESAbsoluteMPFBiasDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESAbsoluteScaleUp",jetE[5],"jetE_JESAbsoluteScaleUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESAbsoluteScaleDown",jetE[6],"jetE_JESAbsoluteScaleDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESAbsoluteStatUp",jetE[7],"jetE_JESAbsoluteStatUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESAbsoluteStatDown",jetE[8],"jetE_JESAbsoluteStatDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESFlavorQCDUp",jetE[9],"jetE_JESFlavorQCDUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESFlavorQCDDown",jetE[10],"jetE_JESFlavorQCDDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESFragmentationUp",jetE[11],"jetE_JESFragmentationUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESFragmentationDown",jetE[12],"jetE_JESFragmentationDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESPileUpDataMCUp",jetE[13],"jetE_JESPileUpDataMCUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESPileUpDataMCDown",jetE[14],"jetE_JESPileUpDataMCDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESPileUpPtBBUp",jetE[15],"jetE_JESPileUpPtBBUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESPileUpPtBBDown",jetE[16],"jetE_JESPileUpPtBBDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESPileUpPtEC1Up",jetE[17],"jetE_JESPileUpPtEC1Up["+TString("nJetMax")+"]/F");
  Book("jetE_JESPileUpPtEC1Down",jetE[18],"jetE_JESPileUpPtEC1Down["+TString("nJetMax")+"]/F");
  Book("jetE_JESPileUpPtEC2Up",jetE[19],"jetE_JESPileUpPtEC2Up["+TString("nJetMax")+"]/F");
  Book("jetE_JESPileUpPtEC2Down",jetE[20],"jetE_JESPileUpPtEC2Down["+TString("nJetMax")+"]/F");
  Book("jetE_JESPileUpPtRefUp",jetE[21],"jetE_JESPileUpPtRefUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESPileUpPtRefDown",jetE[22],"jetE_JESPileUpPtRefDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativeFSRUp",jetE[23],"jetE_JESRelativeFSRUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativeFSRDown",jetE[24],"jetE_JESRelativeFSRDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativeJEREC1Up",jetE[25],"jetE_JESRelativeJEREC1Up["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativeJEREC1Down",jetE[26],"jetE_JESRelativeJEREC1Down["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativePtBBUp",jetE[27],"jetE_JESRelativePtBBUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativePtBBDown",jetE[28],"jetE_JESRelativePtBBDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativePtEC1Up",jetE[29],"jetE_JESRelativePtEC1Up["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativePtEC1Down",jetE[30],"jetE_JESRelativePtEC1Down["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativePtEC2Up",jetE[31],"jetE_JESRelativePtEC2Up["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativePtEC2Down",jetE[32],"jetE_JESRelativePtEC2Down["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativeStatECUp",jetE[33],"jetE_JESRelativeStatECUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativeStatECDown",jetE[34],"jetE_JESRelativeStatECDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativeStatFSRUp",jetE[35],"jetE_JESRelativeStatFSRUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESRelativeStatFSRDown",jetE[36],"jetE_JESRelativeStatFSRDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESSinglePionECALUp",jetE[37],"jetE_JESSinglePionECALUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESSinglePionECALDown",jetE[38],"jetE_JESSinglePionECALDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESSinglePionHCALUp",jetE[39],"jetE_JESSinglePionHCALUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESSinglePionHCALDown",jetE[40],"jetE_JESSinglePionHCALDown["+TString("nJetMax")+"]/F");
  Book("jetE_JESTimePtEtaUp",jetE[41],"jetE_JESTimePtEtaUp["+TString("nJetMax")+"]/F");
  Book("jetE_JESTimePtEtaDown",jetE[42],"jetE_JESTimePtEtaDown["+TString("nJetMax")+"]/F");
  Book("jetEta",jetEta,"jetEta["+TString("nJetMax")+"]/F");
  Book("jetPhi",jetPhi,"jetPhi["+TString("nJetMax")+"]/F");
  Book("jetGenPt",jetGenPt,"jetGenPt["+TString("nJetMax")+"]/F");
  Book("jetDeepCSV",jetDeepCSV,"jetDeepCSV["+TString("nJetMax")+"]/F");
  Book("jetDeepQG",jetDeepQG,"jetDeepQG["+TString("nJetMax")+"]/F");
  Book("jetFlav",jetFlav,"jetFlav["+TString("nJetMax")+"]/I");
  Book("jetIsTight",jetIsTight,"jetIsTight["+TString("nJetMax")+"]/I");
  Book("jetIsPU",jetIsPU,"jetIsPU["+TString("nJetMax")+"]/I");
  Book("nLoosePhoton",&nLoosePhoton,"nLoosePhoton/I");
  Book("nTightPhoton",&nTightPhoton,"nTightPhoton/I");
  Book("loosePho1IsTight",&loosePho1IsTight,"loosePho1IsTight/I");
  Book("loosePho1Pt",&loosePho1Pt,"loosePho1Pt/F");
  Book("loosePho1Eta",&loosePho1Eta,"loosePho1Eta/F");
  Book("loosePho1Phi",&loosePho1Phi,"loosePho1Phi/F");
  Book("loosePho1r9",&loosePho1r9,"loosePho1r9/F");
  Book("loosePho1chIso",&loosePho1chIso,"loosePho1chIso/F");
  Book("loosePho1nhIso",&loosePho1nhIso,"loosePho1nhIso/F");
  Book("loosePho1phIso",&loosePho1phIso,"loosePho1phIso/F");
  Book("loosePho1hOverE",&loosePho1hOverE,"loosePho1hOverE/F");
  Book("loosePho1sieie",&loosePho1sieie,"loosePho1sieie/F");
  Book("loosePho1SelBit",&loosePho1SelBit,"loosePho1SelBit/I");
  Book("nLooseElectron",&nLooseElectron,"nLooseElectron/I");
  Book("nLooseMuon",&nLooseMuon,"nLooseMuon/I");
  Book("nTightElectron",&nTightElectron,"nTightElectron/I");
  Book("nTightMuon",&nTightMuon,"nTightMuon/I");
  Book("muonPt",muonPt,"muonPt["+TString("nLooseMuon")+"]/F");
  Book("muonEta",muonEta,"muonEta["+TString("nLooseMuon")+"]/F");
  Book("muonPhi",muonPhi,"muonPhi["+TString("nLooseMuon")+"]/F");
  Book("muonSelBit",muonSelBit,"muonSelBit["+TString("nLooseMuon")+"]/I");
  Book("muonPdgId",muonPdgId,"muonPdgId["+TString("nLooseMuon")+"]/I");
  Book("muonD0",muonD0,"muonD0["+TString("nLooseMuon")+"]/F");
  Book("muonDZ",muonDZ,"muonDZ["+TString("nLooseMuon")+"]/F");
  Book("muonIsSoftMuon",muonIsSoftMuon,"muonIsSoftMuon["+TString("nLooseMuon")+"]/I");
  Book("muonCombIso",muonCombIso,"muonCombIso["+TString("nLooseMuon")+"]/F");
  Book("muonSfLoose",muonSfLoose,"muonSfLoose["+TString("nLooseMuon")+"]/F");
  Book("muonSfMedium",muonSfMedium,"muonSfMedium["+TString("nLooseMuon")+"]/F");
  Book("muonSfTight",muonSfTight,"muonSfTight["+TString("nLooseMuon")+"]/F");
  Book("muonSfUnc",muonSfUnc,"muonSfUnc["+TString("nLooseMuon")+"]/F");
  Book("muonSfReco",muonSfReco,"muonSfReco["+TString("nLooseMuon")+"]/F");
  Book("muTrigMatch",muTrigMatch,"muTrigMatch["+TString("nLooseMuon")+"]/I");
  Book("electronPt",electronPt,"electronPt["+TString("nLooseElectron")+"]/F");
  Book("electronEta",electronEta,"electronEta["+TString("nLooseElectron")+"]/F");
  Book("electronPhi",electronPhi,"electronPhi["+TString("nLooseElectron")+"]/F");
  Book("electronSelBit",electronSelBit,"electronSelBit["+TString("nLooseElectron")+"]/I");
  Book("electronPdgId",electronPdgId,"electronPdgId["+TString("nLooseElectron")+"]/I");
  Book("electronPhoMatch",electronPhoMatch,"electronPhoMatch["+TString("nLooseElectron")+"]/I");
  Book("electronLPhoMatch",electronLPhoMatch,"electronLPhoMatch["+TString("nLooseElectron")+"]/I");
  Book("electronSfLoose",electronSfLoose,"electronSfLoose["+TString("nLooseElectron")+"]/F");
  Book("electronSfMedium",electronSfMedium,"electronSfMedium["+TString("nLooseElectron")+"]/F");
  Book("electronSfTight",electronSfTight,"electronSfTight["+TString("nLooseElectron")+"]/F");
  Book("electronSfUnc",electronSfUnc,"electronSfUnc["+TString("nLooseElectron")+"]/F");
  Book("electronSfReco",electronSfReco,"electronSfReco["+TString("nLooseElectron")+"]/F");
  Book("electronSfMvaWP90",electronSfMvaWP90,"electronSfMvaWP90["+TString("nLooseElectron")+"]/F");
  Book("electronSfMvaWP80",electronSfMvaWP80,"electronSfMvaWP80["+TString("nLooseElectron")+"]/F");
  Book("electronD0",electronD0,"electronD0["+TString("nLooseElectron")+"]/F");
  Book("electronDZ",electronDZ,"electronDZ["+TString("nLooseElectron")+"]/F");
  Book("electronNMissingHits",electronNMissingHits,"electronNMissingHits["+TString("nLooseElectron")+"]/I");
  Book("electronTripleCharge",electronTripleCharge,"electronTripleCharge["+TString("nLooseElectron")+"]/I");
  Book("electronCombIso",electronCombIso,"electronCombIso["+TString("nLooseElectron")+"]/F");
  Book("eleTrigMatch",eleTrigMatch,"eleTrigMatch["+TString("nLooseElectron")+"]/I");
  Book("diLepMass",&diLepMass,"diLepMass/F");
  Book("nTau",&nTau,"nTau/I");
  Book("tauPt",tauPt,"tauPt["+TString("nTau")+"]/F");
  Book("tauEta",tauEta,"tauEta["+TString("nTau")+"]/F");
  Book("tauPhi",tauPhi,"tauPhi["+TString("nTau")+"]/F");
  Book("pdfUp",&pdfUp,"pdfUp/F");
  Book("pdfDown",&pdfDown,"pdfDown/F");
  Book("scale",scale,"scale["+TString("6")+"]/F");
  Book("lheHT",&lheHT,"lheHT/F");
  Book("lheNjets",&lheNjets,"lheNjets/I");
  if (is_darkg) {
    Book("genPho1Pt",&genPho1Pt,"genPho1Pt/F");
    Book("genPho1Eta",&genPho1Eta,"genPho1Eta/F");
    Book("genPho1Phi",&genPho1Phi,"genPho1Phi/F");
    Book("vtxNTrk",&vtxNTrk,"vtxNTrk/I");
    Book("vtxScore",&vtxScore,"vtxScore/F");
    Book("vtxChi2",&vtxChi2,"vtxChi2/F");
  }
  if (is_vbf) {
    Book("genMjj",&genMjj,"genMjj/F");
  }
}